### ISSUE TITLE
GraphQL : Blurhash results in malformated UTF-8 characters error

### ISSUE THREAD

**Issue by denisyilmaz** [spacecatninja/craft-imager-x#112]
### I'm submitting a... 

- [x] bug report
- [ ] feature request
- [ ] general question

### Steps to reproduce

1. Query for a entry with image asset attached
2. On image field, use this `@imagerTransform`: `blurhash: url @imagerTransform (width: 100, height: 100, mode: "crop", format: "jpg", return: "blurhash")`

### Displayed errors, stack trace, relevant logs  

```
{
  "name": "Exception",
  "message": "Malformed UTF-8 characters, possibly incorrectly encoded.",
  "code": 5,
  "type": "yii\\base\\InvalidArgumentException",
  "file": "/var/www/html/vendor/yiisoft/yii2/helpers/BaseJson.php",
  "line": 133,
  "stack-trace": [
    "#0 /var/www/html/vendor/yiisoft/yii2/helpers/BaseJson.php(67): yii\\helpers\\BaseJson::handleJsonError(5)",
    "#1 /var/www/html/vendor/yiisoft/yii2/web/JsonResponseFormatter.php(119): yii\\helpers\\BaseJson::encode(Array, 320)",
    "#2 /var/www/html/vendor/yiisoft/yii2/web/JsonResponseFormatter.php(104): yii\\web\\JsonResponseFormatter->formatJson(Object(craft\\web\\Response))",
    "#3 /var/www/html/vendor/yiisoft/yii2/web/Response.php(1100): yii\\web\\JsonResponseFormatter->format(Object(craft\\web\\Response))",
    "#4 /var/www/html/vendor/craftcms/cms/src/web/Response.php(281): yii\\web\\Response->prepare()",
    "#5 /var/www/html/vendor/yiisoft/yii2/web/Response.php(344): craft\\web\\Response->prepare()",
    "#6 /var/www/html/vendor/yiisoft/yii2/base/Application.php(398): yii\\web\\Response->send()",
    "#7 /var/www/html/web/index.php(27): yii\\base\\Application->run()",
    "#8 {main}"
  ]
}
```

### Additional info

- Imager version & edition: v3.5.1
- PHP version: 7.4.22
- Imagick 3.4.3 (ImageMagick 6.9.10-23)
- Craft Pro 3.7.7

**Comment by aelvan** [comment]
Hi,

I'm not able to reproduce. Does this happen for all assets, or one in particular?
