### ISSUE TITLE
Imager fails when encountering a zero-byte file

### ISSUE THREAD

**Issue by proimage** [spacecatninja/craft-imager-x#124]
### I'm submitting a... 

- [x] bug report
- [ ] feature request
- [ ] general question

### Steps to reproduce

1. Store images on DigitalOcean Spaces
2. Use the "Imager X Storage Driver for DigitalOcean Spaces" plugin to have Imager-X generate transforms of images
3. Somehow end up with zero-byte JPGs in `/storage/runtime/imager/`.
4. Watch the entire page fail to load because Imager-X trips up over the zero-byte file.

### Description
 
On a client's website, every now and then, a zero-byte image file will end up in the above-mentioned directory (technically, it's in the `/var/www/[clientName]/htdocs/storage/runtime/imager/images/766/` directory, but who's counting?). I don't know why this is happening, nor how to cause it to happen on-demand; most of the time, images get copied over from DO Spaced just fine.

However it is happening, when such a zero-byte file is encountered, Imager-X causes the entire page to fail.

While I would love to see the problem that's causing zero-byte files to be created in the first place get resolved, I realize that it could be caused by anything from a network failure to a memory overflow, and is thus nearly impossible to fully prevent. Instead, I would expect that when Imager-X encounters a zero-byte file, perhaps it could try copying the source image over to the local storage folder again. If _that_ fails, then perhaps instead of the entire page failing to load, it would merely be a missing image in the page.

### Displayed errors, stack trace, relevant logs  

```
Next Imagine\Exception\RuntimeException: Unable to open image /var/www/[clientName]/htdocs/storage/runtime/imager/images/766/09_myAwesomeImage_3000.jpg in /var/www/[clientName]/htdocs/vendor/pixelandtonic/imagine/src/Imagick/Imagine.php:77
Stack trace:
#0 /var/www/[clientName]/htdocs/vendor/spacecatninja/imager-x/src/transformers/CraftTransformer.php(210): Imagine\Imagick\Imagine->open()
#1 /var/www/[clientName]/htdocs/vendor/spacecatninja/imager-x/src/transformers/CraftTransformer.php(96): spacecatninja\imagerx\transformers\CraftTransformer->getTransformedImage()
#2 /var/www/[clientName]/htdocs/vendor/spacecatninja/imager-x/src/services/ImagerService.php(472): spacecatninja\imagerx\transformers\CraftTransformer->transform()
#3 /var/www/[clientName]/htdocs/vendor/spacecatninja/imager-x/src/variables/ImagerVariable.php(38): spacecatninja\imagerx\services\ImagerService->transformImage()
#4 /var/www/[clientName]/htdocs/vendor/twig/twig/src/Extension/CoreExtension.php(1511): spacecatninja\imagerx\variables\ImagerVariable->transformImage()
#5 /var/www/[clientName]/htdocs/vendor/craftcms/cms/src/helpers/Template.php(106): twig_get_attribute()
#6 /mnt/[serverName]/[clientName]/htdocs/storage/runtime/compiled_templates/91/9198990393ae64be8e9dc080523a50556f995bc28db7caf51aa89c3c3512a5ed.php(88): craft\helpers\Template::attribute()
#7 /var/www/[clientName]/htdocs/vendor/twig/twig/src/Template.php(405): __TwigTemplate_7b219f74f655bb76b2e758637b1c46c3749b8c84026100201dbbac352c9f08cf->doDisplay()
#8 /var/www/[clientName]/htdocs/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling()
#9 /mnt/[serverName]/[clientName]/htdocs/storage/runtime/compiled_templates/92/92da12e312a41f091a506874a28519050a76679aba610b756e9314dbd4faf4c2.php(88): Twig\Template->display()
#10 /var/www/[clientName]/htdocs/vendor/twig/twig/src/Template.php(182): __TwigTemplate_f38e9c39f82310e2476badab7fb2a8b979ec0915d399ee0f05c01c33b90732af->block_content()
#11 /mnt/[serverName]/[clientName]/htdocs/storage/runtime/compiled_templates/10/10411c148d75d911bd5070f7291d3fb910b28cf417790c4cb79340477af35f40.php(255): Twig\Template->displayBlock()
#12 /var/www/[clientName]/htdocs/vendor/twig/twig/src/Template.php(405): __TwigTemplate_30a4d1006a884ba6c15974ca537283874450693b18ff597372f871592526af4f->doDisplay()
#13 /var/www/[clientName]/htdocs/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling()
#14 /mnt/[serverName]/[clientName]/htdocs/storage/runtime/compiled_templates/92/92da12e312a41f091a506874a28519050a76679aba610b756e9314dbd4faf4c2.php(50): Twig\Template->display()
#15 /var/www/[clientName]/htdocs/vendor/twig/twig/src/Template.php(405): __TwigTemplate_f38e9c39f82310e2476badab7fb2a8b979ec0915d399ee0f05c01c33b90732af->doDisplay()
#16 /var/www/[clientName]/htdocs/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling()
#17 /var/www/[clientName]/htdocs/vendor/twig/twig/src/Template.php(390): Twig\Template->display()
#18 /var/www/[clientName]/htdocs/vendor/twig/twig/src/TemplateWrapper.php(45): Twig\Template->render()
#19 /var/www/[clientName]/htdocs/vendor/twig/twig/src/Environment.php(318): Twig\TemplateWrapper->render()
#20 /var/www/[clientName]/htdocs/vendor/craftcms/cms/src/web/View.php(408): Twig\Environment->render()
#21 /var/www/[clientName]/htdocs/vendor/craftcms/cms/src/web/View.php(461): craft\web\View->renderTemplate()
#22 /var/www/[clientName]/htdocs/vendor/craftcms/cms/src/web/Controller.php(201): craft\web\View->renderPageTemplate()
#23 /var/www/[clientName]/htdocs/vendor/craftcms/cms/src/controllers/TemplatesController.php(102): craft\web\Controller->renderTemplate()
#24 [internal function]: craft\controllers\TemplatesController->actionRender()
#25 /var/www/[clientName]/htdocs/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#26 /var/www/[clientName]/htdocs/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams()
#27 /var/www/[clientName]/htdocs/vendor/yiisoft/yii2/base/Module.php(534): yii\base\Controller->runAction()
#28 /var/www/[clientName]/htdocs/vendor/craftcms/cms/src/web/Application.php(287): yii\base\Module->runAction()
#29 /var/www/[clientName]/htdocs/vendor/yiisoft/yii2/web/Application.php(104): craft\web\Application->runAction()
#30 /var/www/[clientName]/htdocs/vendor/craftcms/cms/src/web/Application.php(272): yii\web\Application->handleRequest()
#31 /var/www/[clientName]/htdocs/vendor/yiisoft/yii2/base/Application.php(392): craft\web\Application->handleRequest()
#32 /var/www/[clientName]/htdocs/web/index.php(23): yii\base\Application->run()
#33 {main}
```

### Additional info

- Imager version & edition: Imager X v3.5.3
- Imager transformer: ?
- Craft version: Craft Pro 3.7.18.2
- PHP version: 7.4.3
- Image driver & version: Imagick 3.4.4 (ImageMagick 6.9.10-23)
- Database driver & version: MySQL 8.0.26
- Plugins & versions (if relevant):
    - DigitalOcean Spaces Volume	1.1.3
    - Imager X	v3.5.3
    - Imager X Storage Driver for DigitalOcean Spaces	2.0.0

**Comment by aelvan** [comment]
There is a bug related to the exception not being caught by `suppressExceptions` which I will fix. 
Will also try to account for zero byte files being created by the volume.

**Comment by aelvan** [comment]
The bug where the exception wasn't caught has been fix. So if you have `'suppressExceptions' => true` (default), it should no longer throw an exception. But imager will return `null` instead of transformed images, so you still need to deal with that somehow.

I will get back to the issue regarding handling of zero byte files and see if it's possible to counter that.

**Comment by aelvan** [comment]
Version 3.5.5 implements a couple of fixes that should reduce the chance of corrupt files being stuck in the cache.
