### ISSUE TITLE
[Craft CMS 4] CLI Commands for generating Images throw an error

### ISSUE THREAD

**Issue by davidhellmann** [spacecatninja/craft-imager-x#136]
### I'm submitting a... 

- [ x ] bug report

### Steps to reproduce

1. ... Tried to generate transforms via CLI with this command: `php craft imager-x/generate/index -v=images` 

### Displayed errors, stack trace, relevant logs  

```
Exception 'Error' with message 'Typed property spacecatninja\imagerx\console\controllers\GenerateController::$volume must not be accessed before initialization'

in /Users/david.hellmann/Development/Private/craftcms-baukasten/vendor/yiisoft/yii2/console/Controller.php:153

Stack trace:
#0 /Users/david.hellmann/Development/Private/craftcms-baukasten/vendor/yiisoft/yii2/base/Module.php(552): yii\console\Controller->runAction('index', Array)
#1 /Users/david.hellmann/Development/Private/craftcms-baukasten/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('imager-x/genera...', Array)
#2 /Users/david.hellmann/Development/Private/craftcms-baukasten/vendor/craftcms/cms/src/console/Application.php(90): yii\console\Application->runAction('imager-x/genera...', Array)
#3 /Users/david.hellmann/Development/Private/craftcms-baukasten/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('imager-x/genera...', Array)
#4 /Users/david.hellmann/Development/Private/craftcms-baukasten/vendor/yiisoft/yii2/base/Application.php(384): yii\console\Application->handleRequest(Object(craft\console\Request))
#5 /Users/david.hellmann/Development/Private/craftcms-baukasten/craft(22): yii\base\Application->run()
#6 {main}
```

### Additional info

- Imager version & edition: 4.0.0-beta.1 / pro
- Imager transformer: Craft
- Craft version: Craft CMS 4 Beta 4
- PHP version: 8.1
- Image driver & version: Imagick 3.7.0 (ImageMagick 7.1.0-29)
- Database driver & version: MySQL 8

**Comment by aelvan** [comment]
Should be fixed in beta.2

**Comment by davidhellmann** [comment]
works, thanks!
