### ISSUE TITLE
Error trying to access Utilities in Craft4

### ISSUE THREAD

**Issue by MattWilcox** [spacecatninja/craft-imager-x#148]
### I'm submitting a... 

- [ x] bug report
- [ ] feature request
- [ ] general question

### Steps to reproduce
Try to load https://DOMAIN/admin/utilities/imager-x-utility
e.g., Utilities > Imager X 

### Description
![Screenshot 2022-05-04 at 11 18 18](https://user-images.githubusercontent.com/814039/166663695-ceb561e8-33e5-4b79-8322-fa0bcb4f2a8a.jpg)

### Displayed errors, stack trace, relevant logs  

```
2022-05-04 10:28:45 [web.INFO] [yii\db\Connection::open] Opening DB connection: mysql:host=mysql-5.7-3306.database.nitro;dbname=craft4test;port=3306 {"memory":8767816} 
2022-05-04 10:28:45 [web.INFO] [yii\web\Session::open] Session started {"memory":11959552} 
2022-05-04 10:28:45 [web.INFO] [nystudio107\minify\Minify::init] Minify plugin loaded {"memory":16993120} 
2022-05-04 10:28:45 [web.INFO] [nystudio107\seomatic\Seomatic::init] SEOmatic plugin loaded {"memory":18798680} 
2022-05-04 10:28:45 [web.ERROR] [UnexpectedValueException] UnexpectedValueException: RecursiveDirectoryIterator::__construct(/app/storage/runtime/imager): Failed to open directory: No such file or directory in /app/vendor/spacecatninja/imager-x/src/helpers/FileHelper.php:27
Stack trace:
#0 /app/vendor/spacecatninja/imager-x/src/helpers/FileHelper.php(27): RecursiveDirectoryIterator->__construct('/app/storage/ru...')
#1 /app/vendor/spacecatninja/imager-x/src/utilities/ImagerUtility.php(85): spacecatninja\imagerx\helpers\FileHelper::filesInPath('/app/storage/ru...')
#2 /app/vendor/craftcms/cms/src/controllers/UtilitiesController.php(90): spacecatninja\imagerx\utilities\ImagerUtility::contentHtml()
#3 [internal function]: craft\controllers\UtilitiesController->actionShowUtility('imager-x-utilit...')
#4 /app/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#5 /app/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#6 /app/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('show-utility', Array)
#7 /app/vendor/craftcms/cms/src/web/Application.php(301): yii\base\Module->runAction('utilities/show-...', Array)
#8 /app/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('utilities/show-...', Array)
#9 /app/vendor/craftcms/cms/src/web/Application.php(286): yii\web\Application->handleRequest(Object(craft\web\Request))
#10 /app/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest(Object(craft\web\Request))
#11 /app/web/index.php(12): yii\base\Application->run()
#12 {main} {"memory":23741592,"exception":"[object] (UnexpectedValueException(code: 0): RecursiveDirectoryIterator::__construct(/app/storage/runtime/imager): Failed to open directory: No such file or directory at /app/vendor/spacecatninja/imager-x/src/helpers/FileHelper.php:27)"} 
2022-05-04 10:28:45 [web.INFO] [application] Request context:


```

### Additional info

Latest everything, Craft4 beta.

**Comment by aelvan** [comment]
That's... weird. Is `/app/storage` your actual storage folder? Is it symlinked? Is this in Nitro?

**Comment by aelvan** [comment]
I wasn't able to get my nitro install working today, so didn't get to do a test there. But I've added some bandaids, and a possible fix that's in 4.0.0. You should now either see file counts and sizes per cache in the utility (if I managed to fix it), or at least get no error and a "-" instead of numbers. Let me know how it looks.

**Comment by MattWilcox** [comment]
Yep that's fixed it, thanks.
I've not symlinked anything, so it may be a consequence of how Nitro works?

**Comment by aelvan** [comment]
Yep, a `realpath` around the path fixed it, which probably makes sense because of docker.
