### ISSUE TITLE
Cannot assign array to property Settings::$imagerUrl of type string

### ISSUE THREAD

**Issue by Jan10** [spacecatninja/craft-imager-x#150]
### I'm submitting a... 

- [x] bug report
- [ ] feature request
- [ ] general question

### Steps to reproduce

1. Use `imagerUrl` array

```
'imagerUrl' => [
    'siteOneHandle' => 'http://one.pullproxy.com/',
    'siteTwoHandle' => 'http://two.pullproxy.com/',
],
```
2. Type Error Cannot assign array to property spacecatninja\imagerx\models\Settings::$imagerUrl of type string appears

### Description
 
When I use the `imagerUrl` array I get an error.

### Displayed errors, stack trace, relevant logs  

```
TypeError: Cannot assign array to property spacecatninja\imagerx\models\Settings::$imagerUrl of type string in /app/vendor/yiisoft/yii2/base/Model.php:741
Stack trace:
#0 /app/vendor/craftcms/cms/src/base/Model.php(220): yii\base\Model->setAttributes(Array, false)
#1 /app/vendor/craftcms/cms/src/base/Plugin.php(193): craft\base\Model->setAttributes(Array, false)
#2 /app/vendor/yiisoft/yii2/base/Component.php(180): craft\base\Plugin->setSettings(Array)
#3 /app/vendor/yiisoft/yii2/BaseYii.php(558): yii\base\Component->__set('settings', Array)
#4 /app/vendor/yiisoft/yii2/base/BaseObject.php(107): yii\BaseYii::configure(Object(spacecatninja\imagerx\ImagerX), Array)
#5 /app/vendor/yiisoft/yii2/base/Module.php(161): yii\base\BaseObject->__construct(Array)
#6 /app/vendor/craftcms/cms/src/base/Plugin.php(122): yii\base\Module->__construct('imager-x', Object(craft\web\Application), Array)
#7 [internal function]: craft\base\Plugin->__construct('imager-x', Object(craft\web\Application), Array)
#8 /app/vendor/yiisoft/yii2/di/Container.php(419): ReflectionClass->newInstanceArgs(Array)
#9 /app/vendor/yiisoft/yii2/di/Container.php(170): yii\di\Container->build('spacecatninja\\i...', Array, Array)
#10 /app/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get('spacecatninja\\i...', Array, Array)
#11 /app/vendor/craftcms/cms/src/Craft.php(53): yii\BaseYii::createObject(Array, Array)
#12 /app/vendor/craftcms/cms/src/services/Plugins.php(949): Craft::createObject(Array, Array)
#13 /app/vendor/craftcms/cms/src/services/Plugins.php(228): craft\services\Plugins->createPlugin('imager-x', Array)
#14 /app/vendor/craftcms/cms/src/base/ApplicationTrait.php(1471): craft\services\Plugins->loadPlugins()
#15 /app/vendor/craftcms/cms/src/web/Application.php(105): craft\web\Application->_postInit()
#16 /app/vendor/yiisoft/yii2/base/BaseObject.php(109): craft\web\Application->init()
#17 /app/vendor/yiisoft/yii2/base/Application.php(204): yii\base\BaseObject->__construct(Array)
#18 [internal function]: yii\base\Application->__construct(Array)
#19 /app/vendor/yiisoft/yii2/di/Container.php(419): ReflectionClass->newInstanceArgs(Array)
#20 /app/vendor/yiisoft/yii2/di/Container.php(170): yii\di\Container->build('craft\\web\\Appli...', Array, Array)
#21 /app/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get('craft\\web\\Appli...', Array, Array)
#22 /app/vendor/craftcms/cms/src/Craft.php(53): yii\BaseYii::createObject(Array, Array)
#23 /app/vendor/craftcms/cms/bootstrap/bootstrap.php(239): Craft::createObject(Array)
#24 /app/vendor/craftcms/cms/bootstrap/web.php(40): require('/app/vendor/cra...')
#25 /app/web/index.php(21): require('/app/vendor/cra...')
#26 {main}
```

### Additional info

- Imager version & edition: 4.0.0 Pro
- Craft version: Craft Pro 4.0.3
- PHP version: 8.0.16
- Image driver & version: Imagick 3.7.0 (ImageMagick 7.1.0-16)

**Comment by aelvan** [comment]
Thanks for reporting, this has been fixed in 4.0.1.
