### ISSUE TITLE
Upgrade to v3.6.2 failing

### ISSUE THREAD

**Issue by jwb009** [spacecatninja/craft-imager-x#163]
### I'm submitting a... 

- [X] bug report
- [ ] feature request
- [ ] general question

### Steps to reproduce

1. Upgrade from 3.5.8 to 3.6.2
2. ...
3. ...

### Description
 
The upgrade fails with the stack trace as below:

### Displayed errors, stack trace, relevant logs  

```
Performing one update:

    - imager-x v3.5.8 => v3.6.2

Create database backup? (yes|no) [yes]:
Backing up the database ... done
Performing update with Composer ... done
Applying new migrations ... error: The command "'/usr/bin/php8.0' '/var/www/html/craft' 'migrate/all' '--no-backup' '--no-content'" failed.

Exit Code: 1(General error)

Working directory: /var/www/html

Output:
================


Error Output:
================
Exception 'yii\base\UnknownPropertyException' with message 'Getting unknown property: spacecatninja\imagerx\models\ConfigModel::registerCacheOptions'

in /var/www/html/vendor/yiisoft/yii2/base/Component.php:154

Stack trace:
#0 /var/www/html/vendor/spacecatninja/imager-x/src/ImagerX.php(322): yii\base\Component->__get('registerCacheOp...')
#1 /var/www/html/vendor/spacecatninja/imager-x/src/ImagerX.php(252): spacecatninja\imagerx\ImagerX->registerCacheOptions()
#2 [internal function]: spacecatninja\imagerx\ImagerX->spacecatninja\imagerx\{closure}(Object(yii\base\Event))
#3 /var/www/html/vendor/yiisoft/yii2/base/Event.php(312): call_user_func(Object(Closure), Object(yii\base\Event))
#4 /var/www/html/vendor/yiisoft/yii2/base/Component.php(642): yii\base\Event::trigger('craft\\services\\...', 'afterLoadPlugin...', Object(yii\base\Event))
#5 /var/www/html/vendor/craftcms/cms/src/services/Plugins.php(278): yii\base\Component->trigger('afterLoadPlugin...')
#6 /var/www/html/vendor/craftcms/cms/src/base/ApplicationTrait.php(1487): craft\services\Plugins->loadPlugins()
#7 /var/www/html/vendor/craftcms/cms/src/console/Application.php(48): craft\console\Application->_postInit()
#8 /var/www/html/vendor/yiisoft/yii2/base/BaseObject.php(109): craft\console\Application->init()
#9 /var/www/html/vendor/yiisoft/yii2/base/Application.php(204): yii\base\BaseObject->__construct(Array)
#10 /var/www/html/vendor/yiisoft/yii2/console/Application.php(89): yii\base\Application->__construct(Array)
#11 [internal function]: yii\console\Application->__construct(Array)
#12 /var/www/html/vendor/yiisoft/yii2/di/Container.php(419): ReflectionClass->newInstanceArgs(Array)
#13 /var/www/html/vendor/yiisoft/yii2/di/Container.php(170): yii\di\Container->build('craft\\console\\A...', Array, Array)
#14 /var/www/html/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get('craft\\console\\A...', Array, Array)
#15 /var/www/html/vendor/craftcms/cms/src/Craft.php(61): yii\BaseYii::createObject(Array, Array)
#16 /var/www/html/vendor/craftcms/cms/bootstrap/bootstrap.php(247): Craft::createObject(Array)
#17 /var/www/html/vendor/craftcms/cms/bootstrap/console.php(51): require('/var/www/html/v...')
#18 /var/www/html/craft(26): require('/var/www/html/v...')
#19 {main}
```

### Additional info

- Imager version & edition: 3.6.2
- Imager transformer: Imgix
- Craft version: 3.7.50
- PHP version: 8.0
- Image driver & version: Imagick 3.5.1 (ImageMagick 6.9.11-60)

**Comment by aelvan** [comment]
Hi,

The config setting that's reported missing, `registerCacheOptions`, was introduced in 3.6.0, and is definitely there. Either your install was somehow borked so that Settings.php wasn't correctly updated, or you have a cached version of the settings either in Craft's cache, or PHP's opcache, whoch is being used. 

How are you performing the upgrade?

**Comment by jwb009** [comment]
I tried upgrading both in the control panel and CLI...same result. This is on a local DDEV install, if it matters.

**Comment by aelvan** [comment]
That is weird. Did you try restarting php-fpm?

**Comment by jwb009** [comment]
Yes, restarted everything...same result.

**Comment by jwb009** [comment]
OK, got it working. I had to manually add `public $registerCacheOptions = false;` to my `config/imager-x.php` file. With that line added, the upgrade worked.

**Comment by aelvan** [comment]
Yeah, that shouldn't be necessary. I'll do some more testing to try to reproduce. Could you post the contents of your `imager-x.php` (make sure to redact any sensitive details)?

**Comment by jwb009** [comment]
```<?php
/**
 * Imager X plugin for Craft CMS
 *
 * Ninja powered image transforms.
 *
 * @link      https://www.spacecat.ninja
 * @copyright Copyright (c) 2020 André Elvan
 */

namespace spacecatninja\imagerx\models;

use craft\helpers\ConfigHelper;
use craft\helpers\FileHelper;
use craft\base\Model;
use Yii;

class Settings extends Model
{
    public $transformer = 'imgix';
    public $imagerSystemPath = '@webroot/imager/';
    public $imagerUrl = '****';
    
    public $cacheEnabled = false;
    public $cacheRemoteFiles = false;
    public $cacheDuration = 1209600;
    public $cacheDurationRemoteFiles = 1209600;
    public $cacheDurationExternalStorage = 1209600;
    public $cacheDurationNonOptimized = 300;
    public $registerCacheOptions = false;

    public $jpegQuality = 80;
    public $pngCompressionLevel = 2;
    public $webpQuality = 80;
    public $avifQuality = 80;
    public $jxlQuality = 80;
    
    public $webpImagickOptions = [];
    public $interlace = false;
    public $allowUpscale = true;
    public $resizeFilter = 'lanczos';
    public $smartResizeEnabled = false;
    public $removeMetadata = false;
    public $preserveColorProfiles = false;
    public $safeFileFormats = ['jpg', 'jpeg', 'gif', 'png'];
    public $bgColor = '';
    public $position = '50% 50%';
    public $letterbox = ['color' => '#000', 'opacity' => 0];
    public $useFilenamePattern = true;
    public $filenamePattern = '{basename}_{transformString|hash}.{extension}';
    public $shortHashLength = 10;
    public $hashFilename = 'postfix'; // deprecated
    public $hashPath = false;
    public $addVolumeToPath = true;
    public $hashRemoteUrl = false;
    public $useRemoteUrlQueryString = false;
    public $instanceReuseEnabled = false;
    public $noop = false;
    public $suppressExceptions = false;
    public $convertToRGB = false;
    public $skipExecutableExistCheck = false;
    public $removeTransformsOnAssetFileops = false;
    public $curlOptions = [];
    public $runJobsImmediatelyOnAjaxRequests = true;
    public $fillTransforms = false;
    public $fillAttribute = 'width';
    public $fillInterval = '200';
    public $fallbackImage = null;
    public $mockImage = null;
    public $useRawExternalUrl = true;
    public $clearKey = '';

    public $useForNativeTransforms = false;
    public $useForCpThumbs = false;
    public $hideClearCachesForUserGroups = [];

    public $imgixProfile = 'default';
    public $imgixApiKey = '';
    public $imgixEnableAutoPurging = true;
    public $imgixEnablePurgeElementAction = true;
    public $imgixConfig = [
        'default' => [
			'domain' => '****',
            'useHttps' => true,
            'signKey' => '',
            'sourceIsWebProxy' => false,
            'useCloudSourcePath' => true,
            'getExternalImageDimensions' => true,
            'defaultParams' => ['auto'=>'compress,format', 'cs'=> 'srgb'],
            'apiKey' => '****',
            'excludeFromPurge' => false,
        ]
    ];

    public $optimizeType = 'job';
    public $optimizers = [];
    public $optimizerConfig = [
        'jpegoptim' => [
            'extensions' => ['jpg'],
            'path' => '/usr/bin/jpegoptim',
            'optionString' => '-s',
        ],
        'jpegtran' => [
            'extensions' => ['jpg'],
            'path' => '/usr/bin/jpegtran',
            'optionString' => '-optimize -copy none',
        ],
        'mozjpeg' => [
            'extensions' => ['jpg'],
            'path' => '/usr/bin/mozjpeg',
            'optionString' => '-optimize -copy none',
        ],
        'optipng' => [
            'extensions' => ['png'],
            'path' => '/usr/bin/optipng',
            'optionString' => '-o2',
        ],
        'pngquant' => [
            'extensions' => ['png'],
            'path' => '/usr/bin/pngquant',
            'optionString' => '--strip --skip-if-larger',
        ],
        'gifsicle' => [
            'extensions' => ['gif'],
            'path' => '/usr/bin/gifsicle',
            'optionString' => '--optimize=3 --colors 256',
        ],
        'tinypng' => [
            'extensions' => ['png', 'jpg'],
            'apiKey' => '',
        ],
        'kraken' => [
            'extensions' => ['png', 'jpg', 'gif'],
            'apiKey' => '',
            'apiSecret' => '',
            'additionalParams' => [
                'lossy' => true,
            ]
        ],
        'imageoptim' => [
            'extensions' => ['png', 'jpg', 'gif'],
            'apiUsername' => '',
            'quality' => 'medium'
        ],
    ];

    public $storages = [];
    public $storageConfig = [
        'aws' => [
			'accessKey' => '****',
            'secretAccessKey' => '****',
            'region' => '****',
            'bucket' => '****',
            'folder' => '****',
            'requestHeaders' => array(),
            'storageType' => 'standard',
            'cloudfrontInvalidateEnabled' => false,
            'cloudfrontDistributionId' => '',
            'public' => 'true',
        ],
        'gcs' => [
            'keyFile' => '',
            'bucket' => '',
            'folder' => '',
        ],
    ];

    public $customEncoders = [];
    public $transformerConfig = null;
    
    /* deprecated */
    public $useCwebp = false;
    public $cwebpPath = '/usr/bin/cwebp';
    public $cwebpOptions = '';
    public $avifEncoderPath = '';
    public $avifEncoderOptions = [];
    public $avifConvertString = '{src} {dest}';
    
    
    /**
     * Settings constructor.
     *
     * @param array $config
     */
    public function __construct($config = [])
    {
        parent::__construct($config);

        if (!empty($config)) {
            Yii::configure($this, $config);
        }

        $this->init();
    }

    public function init()
    {
        // Set default based on devMode. Overridable through config.  
        $this->suppressExceptions = !\Craft::$app->getConfig()->getGeneral()->devMode;
    }
}```

**Comment by aelvan** [comment]
Oh, do you have all of this in the imager-x.php config file? If so, that explains it. 

The config file should follow the structure of [Craft's config files](https://craftcms.com/docs/3.x/config/config-settings.html), where it should return an array with the settings you want to override, like:

```
<?php
return [
    '*' => [
        'transformer' => 'imgix',
        ...
    ]
];
```

With what you have now, you're redefining Imager's Settings model, so the new changes are overridden.
