### ISSUE TITLE
Issue transforming external image

### ISSUE THREAD

**Issue by mark-adigital** [spacecatninja/craft-imager-x#184]
Hi,

I'm submitting a bug report.

1. Try to transform an image from the Eventbrite API, for example: `https://img.evbuc.com/https%3A%2F%2Fcdn.evbuc.com%2Fimages%2F372052839%2F543193880685%2F1%2Foriginal.20221012-143745?auto=format%2Ccompress&q=75&sharp=10&s=337ac9ecddfce644aaa9926c6b4135fe`

Expected behaviour would be for the image to be transformed as follows:

```
{% set imageUrl = event.logo.original.url|default('\/assets\/img\/arnside.jpg') %}
{% set transformedImages = craft.imager.transformImage(imageUrl, [
  { width: 382 },
  { width: 466 },
  { width: 592 },
  { width: 764 },
  { width: 932 },
  { width: 1184 }
], { ratio: 16/10, interlace: true, format: format }) %}
<img src="{{ transformedImages[0] }}" srcset="{{ craft.imager.srcset(transformedImages) }}" width="382" height="239" sizes="(min-width: 1024px) 382px, (min-width: 640px) 50vw, 100vw" alt="{{ event.name.text|default('Arnside') }}" class="block w-full" crossorigin loading="lazy">
```

However, instead we're seeing intermittent 500 errors due to the image format not being determined. Often these are resolved on refresh (the output is being cached) and the transforms do appear to be working from Eventbrite images, so unsure as to whether this is possibly a false error that is being thrown?

Error log:

```
2022-10-30 12:56:06 [-][-][-][error][Imagine\Exception\InvalidArgumentException] Imagine\Exception\InvalidArgumentException: Saving image in "20221012-143745" format is not supported, please use one of the following extensions: "bmp", "gif", "jpeg", "png", "wbmp", "webp", "xbm" in /srv/users/morecambebay/apps/mbp-live/vendor/pixelandtonic/imagine/src/Gd/Image.php:602
Stack trace:
#0 /srv/users/morecambebay/apps/mbp-live/vendor/pixelandtonic/imagine/src/Gd/Image.php(265): Imagine\Gd\Image->saveOrOutput('20221012-143745', Array, '/srv/users/more...')
#1 /srv/users/morecambebay/apps/mbp-live/vendor/spacecatninja/imager-x/src/transformers/CraftTransformer.php(297): Imagine\Gd\Image->save('/srv/users/more...', Array)
#2 /srv/users/morecambebay/apps/mbp-live/vendor/spacecatninja/imager-x/src/transformers/CraftTransformer.php(96): spacecatninja\imagerx\transformers\CraftTransformer->getTransformedImage(Object(spacecatninja\imagerx\models\LocalSourceImageModel), Array)
#3 /srv/users/morecambebay/apps/mbp-live/vendor/spacecatninja/imager-x/src/services/ImagerService.php(472): spacecatninja\imagerx\transformers\CraftTransformer->transform('https://img.evb...', Array)
#4 /srv/users/morecambebay/apps/mbp-live/vendor/spacecatninja/imager-x/src/variables/ImagerVariable.php(38): spacecatninja\imagerx\services\ImagerService->transformImage('https://img.evb...', Array, Array, NULL)
#5 /srv/users/morecambebay/apps/mbp-live/vendor/twig/twig/src/Extension/CoreExtension.php(1566): spacecatninja\imagerx\variables\ImagerVariable->transformImage('https://img.evb...', Array, Array)
#6 /srv/users/morecambebay/apps/mbp-live/vendor/craftcms/cms/src/helpers/Template.php(106): twig_get_attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(spacecatninja\imagerx\variables\ImagerVariable), 'transformImage', Array, 'method', false, false)
#7 /srv/users/morecambebay/apps/mbp-live/storage/runtime/compiled_templates/1d/1dd842817b8cea5156cee73a9fc6a63d1f59be001d5bc294ac534323584434a0.php(217): craft\helpers\Template::attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(spacecatninja\imagerx\variables\ImagerVariable), 'transformImage', Array, 'method')
#8 /srv/users/morecambebay/apps/mbp-live/vendor/twig/twig/src/Template.php(182): __TwigTemplate_aef5251ad2dabae682481012d3f7e970c4ce6741f4d65520419b66aa5be20ff7->block_maincontent(Array, Array)
#9 /srv/users/morecambebay/apps/mbp-live/storage/runtime/compiled_templates/1c/1cf1f9149b50e31d27a0235c1303d0079700eb51d5d3c1558e0544ef47af3cdb.php(304): Twig\Template->displayBlock('maincontent', Array, Array)
#10 /srv/users/morecambebay/apps/mbp-live/vendor/twig/twig/src/Template.php(405): __TwigTemplate_2e765a7b949dcb64bde8d414f17c42ff9870a60e8691ed1879dd96f517cdfa6d->doDisplay(Array, Array)
#11 /srv/users/morecambebay/apps/mbp-live/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#12 /srv/users/morecambebay/apps/mbp-live/storage/runtime/compiled_templates/1d/1dd842817b8cea5156cee73a9fc6a63d1f59be001d5bc294ac534323584434a0.php(44): Twig\Template->display(Array, Array)
#13 /srv/users/morecambebay/apps/mbp-live/vendor/twig/twig/src/Template.php(405): __TwigTemplate_aef5251ad2dabae682481012d3f7e970c4ce6741f4d65520419b66aa5be20ff7->doDisplay(Array, Array)
#14 /srv/users/morecambebay/apps/mbp-live/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#15 /srv/users/morecambebay/apps/mbp-live/vendor/twig/twig/src/Template.php(390): Twig\Template->display(Array)
#16 /srv/users/morecambebay/apps/mbp-live/vendor/twig/twig/src/TemplateWrapper.php(45): Twig\Template->render(Array, Array)
#17 /srv/users/morecambebay/apps/mbp-live/vendor/twig/twig/src/Environment.php(318): Twig\TemplateWrapper->render(Array)
#18 /srv/users/morecambebay/apps/mbp-live/vendor/craftcms/cms/src/web/View.php(408): Twig\Environment->render('_home/index', Array)
#19 /srv/users/morecambebay/apps/mbp-live/vendor/craftcms/cms/src/web/View.php(461): craft\web\View->renderTemplate('_home/index', Array)
#20 /srv/users/morecambebay/apps/mbp-live/vendor/craftcms/cms/src/web/Controller.php(205): craft\web\View->renderPageTemplate('_home/index', Array, 'site')
#21 /srv/users/morecambebay/apps/mbp-live/vendor/craftcms/cms/src/controllers/TemplatesController.php(102): craft\web\Controller->renderTemplate('_home/index', Array)
#22 [internal function]: craft\controllers\TemplatesController->actionRender('_home/index', Array)
#23 /srv/users/morecambebay/apps/mbp-live/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#24 /srv/users/morecambebay/apps/mbp-live/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#25 /srv/users/morecambebay/apps/mbp-live/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('render', Array)
#26 /srv/users/morecambebay/apps/mbp-live/vendor/craftcms/cms/src/web/Application.php(293): yii\base\Module->runAction('templates/rende...', Array)
#27 /srv/users/morecambebay/apps/mbp-live/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('templates/rende...', Array)
#28 /srv/users/morecambebay/apps/mbp-live/vendor/craftcms/cms/src/web/Application.php(278): yii\web\Application->handleRequest(Object(craft\web\Request))
#29 /srv/users/morecambebay/apps/mbp-live/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest(Object(craft\web\Request))
#30 /srv/users/morecambebay/apps/mbp-live/public/index.php(26): yii\base\Application->run()
#31 {main}```

- Imager version & edition: v3.6.5 Lite
- Imager transformer: Craft
- Craft version: 3.7.57
- PHP version: 7.4
- Image driver & version: GD 7.4.32

Aware this might not be a bug as such, but we would at least appreciate some help to understand the best way to try and fix the issue. Thanks!

**Comment by aelvan** [comment]
Hi,

Thanks for submitting. I'm not able to reproduce, but could you elaborate on this:

> However, instead we're seeing intermittent 500 errors due to the image format not being determined. Often these are resolved on refresh (the output is being cached) and the transforms do appear to be working from Eventbrite images, so unsure as to whether this is possibly a false error that is being thrown?

So, when an image fails, that same image shows correctly on the next refresh?

**Comment by aelvan** [comment]
Could you also share your imager-x config file (make sure to redact any sensitive data).

**Comment by mark-adigital** [comment]
Yes - it certainly seems that way. We've mostly detected the downtime through a Pingdom alert, so by the time we visit the site it's often come back up, but logs indicate that the same image which throws the error will subsequently be transformed successfully.

We're actually just using the default Imager config on this site.

Whenever we're outputting content from EventBrite, we're typically wrapping it in Craft `{% cache %}` tags to reduce the number of calls to the API and improve performance, and the downtime alerts correspond to when that cache expires - but obviously that might not mean the caching is the cause of the problem, just that it might be happening a lot more often without caching.

**Comment by iainb-cogapp** [comment]
I'm seeing the exact same issue when trying to transform images from the Eventbrite API. I'm not sure what exactly is trying to derive the format from the URL. Interestingly, it works fine in my local ddev setup but always errors on our platform.sh preview environment.

**Comment by aelvan** [comment]
@iainb-cogapp I can have a new look at this, but could you add:

1. An url to an image that fails
2. The actual error message with the stack trace
3. The following details:

Imager version & edition: ...
Craft version: ...
PHP version: ...
Image driver & version: ...

Do you get errors consistently or only occasionally like Mark did?

**Comment by iainb-cogapp** [comment]
Hi @aelvan 

Thanks for getting back to me. 

The full URL of the image is: https://img.evbuc.com/https%3A%2F%2Fcdn.evbuc.com%2Fimages%2F140280929%2F525879226627%2F1%2Foriginal.20210630-094748?auto=format%2Ccompress&q=75&sharp=10&s=4038e9060d73103d0131ee848c1e9247

Here's the stack trace:
```
spacecatninja\imagerx\exceptions\ImagerException: Saving image in "20210630-094748" format is not supported, please use one of the following extensions: "gif", "jpeg", "png", "wbmp", "xbm", "bmp", "webp", "avif" in /app/vendor/spacecatninja/imager-x/src/services/ImagerService.php:510
Stack trace:
#0 /app/vendor/spacecatninja/imager-x/src/variables/ImagerVariable.php(33): spacecatninja\imagerx\services\ImagerService->transformImage('https://img.evb...', Array, Array, Array)
#1 /app/vendor/twig/twig/src/Extension/CoreExtension.php(1861): spacecatninja\imagerx\variables\ImagerVariable->transformImage('https://img.evb...', Array, Array, Array)
#2 /app/vendor/craftcms/cms/src/helpers/Template.php(148): Twig\Extension\CoreExtension::getAttribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(spacecatninja\imagerx\variables\ImagerVariable), 'transformImage', Array, 'method', false, false, false, 43)
#3 /app/storage/runtime/compiled_templates/7b/7bf2914c62fc4206644447cb4820bf8f.php(125): craft\helpers\Template::attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(spacecatninja\imagerx\variables\ImagerVariable), 'transformImage', Array, 'method', false, false, false, 43)
#4 /app/vendor/twig/twig/src/Template.php(387): __TwigTemplate_b603f89b55f10bfb89a060a201d2a77a->doDisplay(Array, Array)
#5 /app/storage/runtime/compiled_templates/fb/fb111b18d949dbb3eb4bc788a3edbd77.php(70): Twig\Template->yield(Array)
#6 /app/vendor/twig/twig/src/Template.php(387): __TwigTemplate_ce2bd83f8701e7a00b6910650f0d2707->doDisplay(Array, Array)
#7 /app/storage/runtime/compiled_templates/c0/c0aad417ddf869a29407673ea5534aba.php(136): Twig\Template->yield(Array)
#8 /app/vendor/twig/twig/src/Template.php(431): __TwigTemplate_1d9c659f952cddf6692622ba8408a8bc->block_content(Array, Array)
#9 /app/storage/runtime/compiled_templates/a8/a874962c5b205bbeefe5dec933b6808b.php(279): Twig\Template->yieldBlock('content', Array, Array)
#10 /app/vendor/twig/twig/src/Template.php(387): __TwigTemplate_fec3fec64f4082263ab7c905110cf50a->doDisplay(Array, Array)
#11 /app/storage/runtime/compiled_templates/c0/c0aad417ddf869a29407673ea5534aba.php(87): Twig\Template->yield(Array, Array)
#12 /app/vendor/twig/twig/src/Template.php(387): __TwigTemplate_1d9c659f952cddf6692622ba8408a8bc->doDisplay(Array, Array)
#13 /app/storage/runtime/compiled_templates/a0/a0957e006b381f1777c3186020190256.php(149): Twig\Template->yield(Array)
#14 /app/vendor/twig/twig/src/Template.php(387): __TwigTemplate_083067528036d6fd4201f78e95f62e04->doDisplay(Array, Array)
#15 /app/vendor/twig/twig/src/Template.php(343): Twig\Template->yield(Array, Array)
#16 /app/vendor/twig/twig/src/Template.php(358): Twig\Template->display(Array)
#17 /app/vendor/twig/twig/src/TemplateWrapper.php(35): Twig\Template->render(Array)
#18 /app/vendor/twig/twig/src/Environment.php(320): Twig\TemplateWrapper->render(Array)
#19 /app/vendor/craftcms/cms/src/web/View.php(539): Twig\Environment->render('places/_entry', Array)
#20 /app/vendor/craftcms/cms/src/web/View.php(592): craft\web\View->renderTemplate('places/_entry', Array)
#21 /app/vendor/craftcms/cms/src/web/TemplateResponseFormatter.php(57): craft\web\View->renderPageTemplate('places/_entry', Array, 'site')
#22 /app/vendor/yiisoft/yii2/web/Response.php(1109): craft\web\TemplateResponseFormatter->format(Object(craft\web\Response))
#23 /app/vendor/craftcms/cms/src/web/Response.php(341): yii\web\Response->prepare()
#24 /app/vendor/yiisoft/yii2/web/Response.php(340): craft\web\Response->prepare()
#25 /app/vendor/yiisoft/yii2/base/Application.php(390): yii\web\Response->send()
#26 /app/web/index.php(26): yii\base\Application->run()
#27 {main}
```

Imager version & edition: Pro 4.5.0
Craft version: 4.14.5
PHP version: 8.2.27
Image driver & version: GD 8.2.27

The error is consistent on this environment. Locally my Image driver is "Imagick 3.7.0 (ImageMagick 6.9.11-60)" and the transform works OK. I should be able to switch the image driver, if that's the issue.

**Comment by aelvan** [comment]
@iainb-cogapp Yeah, I'm able to reproduce, it seems like GD is a bit stricter when it comes to the filename it saves to, it has to match the avaiable output format, whereas Imagick just happily outputs whatever, and it works in the browser (see screenshot :))  

![Image](https://github.com/user-attachments/assets/08f5db63-484d-4ec6-b024-ba5f34fea8f3)

So, there's a combination of problems here: 

One is that Imager is not able to determine a file extension for the url, due to how it's constructed, it ends up in a file with extension `.20210630-094748`. Which in itself is not a problem..

But, when setting the extension for the output format, Imager will look at the requested format in the transform, and of that isn't set, the extension of the source file. Meaning that I'm 99% certain that this happens in a transform that doesn't have the `format` transform parameter set. Can you check if that's correct? 

The simplest solution on your end would be to set `format` for all transforms that transforms the external images from Eventbrite. 

On my end, I can't really change the way the file is saved when downloaded (although I see that there's definately room for improvement), because that would break some cached files for existing sites. But I'm thinking that maybe I should set format to jpg by default, if it's not a format that GD can transform. Not sure if there's an easy way to figure that out, but I'll have a look.

But in the meantime, see if you can add `format` to your transforms, and see if that fixes the issue.

**Comment by aelvan** [comment]
That was a fairly easy patch, 4.5.1 should be available now with a fix for this. 

To summarize, if using GD, and no `format` is set on the transform, and the extension from the downloaded external file is not one of the ones that GD can save, Imager will fall back to using `jpg` for `format`.

Hope this helps.
