### ISSUE TITLE
Error when querying assets in GraphQL

### ISSUE THREAD

**Issue by eduardoalonsoalbella** [spacecatninja/craft-imager-x#187]
### I'm submitting a... 

- [x] bug report
- [ ] feature request
- [ ] general question

### Steps to reproduce
The problem is in the function 

```
    /**
     * @param LocalSourceImageModel $source
     *
     * @return array
     */
    public static function getSourceImageSize($source): array
    {
        // Try getimagesize first
        $sourceImageInfo = @getimagesize($source->getFilePath());

        if ($sourceImageInfo[0] !== 0 && $sourceImageInfo[1] !== 0) {
```
 getimagesize can return null, but the following if `$sourceImageInfo[0]` will fail, because it's trying to access an array when the result is boolean

See PR: https://github.com/spacecatninja/craft-imager-x/pull/188

### Displayed errors, stack trace, relevant logs  

```
> yii\base\ErrorException: Trying to access array offset on value of type bool
Stack trace:
#0 /var/app/vendor/spacecatninja/imager-x/src/helpers/ImagerHelpers.php(239): yii\base\ErrorHandler->handleError()
#1 /var/app/vendor/spacecatninja/imager-x/src/models/LocalTransformedImageModel.php(65): spacecatninja\imagerx\helpers\ImagerHelpers::getSourceImageSize()
#2 /var/app/vendor/spacecatninja/imager-x/src/transformers/CraftTransformer.php(304): spacecatninja\imagerx\models\LocalTransformedImageModel->__construct()
#3 /var/app/vendor/spacecatninja/imager-x/src/transformers/CraftTransformer.php(96): spacecatninja\imagerx\transformers\CraftTransformer->getTransformedImage()
#4 /var/app/vendor/spacecatninja/imager-x/src/services/ImagerService.php(472): spacecatninja\imagerx\transformers\CraftTransformer->transform()
#5 /var/app/vendor/spacecatninja/imager-x/src/services/GenerateService.php(303): spacecatninja\imagerx\services\ImagerService->transformImage()
#6 /var/app/vendor/spacecatninja/imager-x/src/jobs/TransformJob.php(64): spacecatninja\imagerx\services\GenerateService->generateTransformsForAsset()
#7 /var/app/vendor/yiisoft/yii2-queue/src/Queue.php(246): spacecatninja\imagerx\jobs\TransformJob->execute()
#8 /var/app/vendor/yiisoft/yii2-queue/src/cli/Queue.php(162): yii\queue\Queue->handleMessage()
#9 /var/app/vendor/yiisoft/yii2-queue/src/cli/Command.php(146): yii\queue\cli\Queue->execute()
#10 [internal function]: yii\queue\cli\Command->actionExec()
#11 /var/app/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#12 /var/app/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams()
#13 /var/app/vendor/yiisoft/yii2/console/Controller.php(182): yii\base\Controller->runAction()
#14 /var/app/vendor/yiisoft/yii2/base/Module.php(552): yii\console\Controller->runAction()
#15 /var/app/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction()
#16 /var/app/vendor/craftcms/cms/src/console/Application.php(89): yii\console\Application->runAction()
#17 /var/app/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction()
#18 /var/app/vendor/craftcms/cms/src/console/Application.php(118): yii\console\Application->handleRequest()
#19 /var/app/vendor/yiisoft/yii2/base/Application.php(384): craft\console\Application->handleRequest()
#20 /var/app/craft(22): yii\base\Application->run()
#21 {main}
```

### Additional info

- Imager version & edition: latest pro
- Imager transformer:
- Craft version: latest
- PHP version: 8.1
- Image driver & version:

**Comment by aelvan** [comment]
Thanks for submitting, your PR has been merged!
