### ISSUE TITLE
DivisionByZero Error when new assets uploaded in v3.6.5

### ISSUE THREAD

**Issue by CaitlinWeb** [spacecatninja/craft-imager-x#203]
### I'm submitting a... 

- [x] bug report
- [ ] feature request
- [ ] general question

### Steps to reproduce

1. Upload a new image such as an animated gif (this is only happening with some images, seems mainly related to animated gifs)
2. Go to the asset volume and folder where the image asset is located
3. DivisionByZero exception is thrown

### Description
 
Saw this merged PR #199 that fixes this but it was for v4. I confirmed that I'm also seeing asset width and height are missing (null) for the problem images. Can the same patch be applied for v3?

Currently we're having to re-index assets (which I assume re-saves the problem images with width and height) when this issue occurs.

### Displayed errors, stack trace, relevant logs  

```
DivisionByZeroError: Caught DivisionByZeroError (500): Division by zero in /app/vendor/spacecatninja/imager-x/src/models/ImgixTransformedImageModel.php:94
#0 /app/vendor/spacecatninja/imager-x/src/transformers/ImgixTransformer.php(116): spacecatninja\imagerx\models\ImgixTransformedImageModel->__construct()
#1 /app/vendor/spacecatninja/imager-x/src/transformers/ImgixTransformer.php(67): spacecatninja\imagerx\transformers\ImgixTransformer->getTransformedImage()
#2 /app/vendor/spacecatninja/imager-x/src/services/ImagerService.php(472): spacecatninja\imagerx\transformers\ImgixTransformer->transform()
#3 /app/vendor/spacecatninja/imager-x/src/ImagerX.php(427): spacecatninja\imagerx\services\ImagerService->transformImage()
#4 [internal function]: spacecatninja\imagerx\ImagerX::spacecatninja\imagerx\{closure}()
#5 /app/vendor/yiisoft/yii2/base/Event.php(312): call_user_func()
#6 /app/vendor/yiisoft/yii2/base/Component.php(642): yii\base\Event::trigger()
#7 /app/vendor/craftcms/cms/src/services/Assets.php(703): yii\base\Component->trigger()
#8 /app/vendor/craftcms/cms/src/elements/Asset.php(1309): craft\services\Assets->getThumbUrl()
#9 /app/vendor/craftcms/cms/src/helpers/Cp.php(319): craft\elements\Asset->getThumbUrl()
#10 /app/vendor/craftcms/cms/src/web/View.php(2127): craft\helpers\Cp::elementHtml()
#11 /app/vendor/craftcms/cms/src/web/View.php(1689): craft\web\View->_getCpElementHtml()
#12 /app/storage/runtime/compiled_templates/35/35a5df784fe788472e8df8ebb1891fcf.php(38): craft\web\View->invokeHook()
#13 /app/vendor/twig/twig/src/Template.php(405): __TwigTemplate_24b38f30317f88887f25e058ffc929bb->doDisplay()
#14 /app/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling()
#15 /app/storage/runtime/compiled_templates/5a/5a8b73580b960d593397ef4a6ecc9d21.php(156): Twig\Template->display()
#16 /app/vendor/twig/twig/src/Template.php(405): __TwigTemplate_0834e0a04b647aa2d2bd1a79b259aaf1->doDisplay()
#17 /app/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling()
#18 /app/storage/runtime/compiled_templates/98/981ecb81b4db00b976b48d54b021dc1b.php(102): Twig\Template->display()
#19 /app/vendor/twig/twig/src/Template.php(405): __TwigTemplate_b24d016819a712dbeecf101a009ea7b6->doDisplay()
#20 /app/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling()
#21 /app/vendor/twig/twig/src/Template.php(390): Twig\Template->display()
#22 /app/vendor/twig/twig/src/TemplateWrapper.php(45): Twig\Template->render()
#23 /app/vendor/twig/twig/src/Environment.php(318): Twig\TemplateWrapper->render()
#24 /app/vendor/craftcms/cms/src/web/View.php(408): Twig\Environment->render()
#25 /app/vendor/craftcms/cms/src/base/Element.php(877): craft\web\View->renderTemplate()
#26 /app/vendor/craftcms/cms/src/controllers/ElementIndexesController.php(541): craft\base\Element::indexHtml()
#27 /app/vendor/craftcms/cms/src/controllers/ElementIndexesController.php(139): craft\controllers\ElementIndexesController->elementResponseData()
#28 [internal function]: craft\controllers\ElementIndexesController->actionGetElements()
#29 /app/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#30 /app/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams()
#31 /app/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction()
#32 /app/vendor/craftcms/cms/src/web/Application.php(293): yii\base\Module->runAction()
#33 /app/vendor/craftcms/cms/src/web/Application.php(602): craft\web\Application->runAction()
#34 /app/vendor/craftcms/cms/src/web/Application.php(272): craft\web\Application->_processActionRequest()
#35 /app/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest()
#36 /app/web/index.php(39): yii\base\Application->run()
#37 {main}
```

### Additional info

- Imager version & edition: 3.6.5 Pro
- Imager transformer: Imgix
- Craft version: 3.7.59
- PHP version: 8.2
- Image driver & version:

**Comment by CaitlinWeb** [comment]
@aelvan This seems like it would be an easy fix and would resolve our production issues when uploading animated gifs. Any chance this could be addressed soon?

**Comment by aelvan** [comment]
Sorry for the late reply. I've added this fix to 3.6.6. Thanks for reporting!
