### ISSUE TITLE
Imager X PDF Adapter failing on files without public URLs

### ISSUE THREAD

**Issue by phrichards** [spacecatninja/craft-imager-x#280]
### I'm submitting a... 

- [x] bug report
- [ ] feature request
- [ ] general question

### Steps to reproduce

1. Create an asset volume with a filesystem that has "Files in this filesystem have public URLs" toggled off
2. Add a PDF to this volume and add the PDF to an entry
3. View the entry

### Description
 
Hi,

We are upgrading a site from Craft 4 to Craft.5 and encountering an issue with Imager X and the PDF adapter. Assets in filesystems that do not have public URLs are throwing an error when viewing their related entry. This worked fine on Craft 4, the error only started after the upgrade.

### Displayed errors, stack trace, relevant logs  

```
TypeError: Cannot assign null to property spacecatninja\imagerx\models\LocalSourceImageModel::$url of type string in /var/www/html/craft3/vendor/spacecatninja/imager-x/src/models/LocalSourceImageModel.php:223
Stack trace:
#0 /var/www/html/craft3/vendor/spacecatninja/imager-x/src/models/LocalSourceImageModel.php(115): spacecatninja\imagerx\models\LocalSourceImageModel->getPathsForLocalAsset(Object(craft\elements\Asset))
#1 /var/www/html/craft3/vendor/spacecatninja/imager-x/src/models/LocalSourceImageModel.php(68): spacecatninja\imagerx\models\LocalSourceImageModel->init(Object(craft\elements\Asset))
#2 /var/www/html/craft3/vendor/spacecatninja/imager-x-pdf-adapter/src/adapters/PDF.php(85): spacecatninja\imagerx\models\LocalSourceImageModel->__construct(Object(craft\elements\Asset))
#3 /var/www/html/craft3/vendor/spacecatninja/imager-x-pdf-adapter/src/adapters/PDF.php(50): spacecatninja\imagerxpdfadapter\adapters\PDF->load(Object(craft\elements\Asset))
#4 /var/www/html/craft3/vendor/spacecatninja/imager-x-pdf-adapter/src/services/PdfLoaderService.php(27): spacecatninja\imagerxpdfadapter\adapters\PDF->__construct(Object(craft\elements\Asset), Array)
#5 /var/www/html/craft3/vendor/spacecatninja/imager-x-pdf-adapter/src/variables/PDFAdapterVariable.php(28): spacecatninja\imagerxpdfadapter\services\PdfLoaderService->loadPdf(Object(craft\elements\Asset), Array)
#6 /var/www/html/craft3/vendor/twig/twig/src/Extension/CoreExtension.php(1802): spacecatninja\imagerxpdfadapter\variables\PDFAdapterVariable->load(Object(craft\elements\Asset), Array)
#7 /var/www/html/craft3/vendor/craftcms/cms/src/helpers/Template.php(148): Twig\Extension\CoreExtension::getAttribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(spacecatninja\imagerxpdfadapter\variables\PDFAdapterVariable), 'load', Array, 'method', false, false, false, 37)
#8 /var/www/html/craft3/storage/runtime/compiled_templates/57/57cf8fb9a1f76af385e609e973a981a2.php(141): craft\helpers\Template::attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(spacecatninja\imagerxpdfadapter\variables\PDFAdapterVariable), 'load', Array, 'method', false, false, false, 37)
#9 /var/www/html/craft3/vendor/twig/twig/src/Template.php(393): __TwigTemplate_591f7cda1c34e22ac0771c771f01db8b->doDisplay(Array, Array)
#10 /var/www/html/craft3/storage/runtime/compiled_templates/1e/1ee0bb3bca9b346ef03c5842f268b3b7.php(587): Twig\Template->yield(Array)
#11 /var/www/html/craft3/vendor/twig/twig/src/Template.php(437): __TwigTemplate_274bcb2d31df53a06f8ac262a82a617a->block_content(Array, Array)
#12 /var/www/html/craft3/storage/runtime/compiled_templates/82/82db0d97f7f999677df45d0c2339997d.php(83): Twig\Template->yieldBlock('content', Array, Array)
#13 /var/www/html/craft3/vendor/twig/twig/src/Template.php(393): __TwigTemplate_1047b7707a34d42ac69e75b15b087f7d->doDisplay(Array, Array)
#14 /var/www/html/craft3/storage/runtime/compiled_templates/1e/1ee0bb3bca9b346ef03c5842f268b3b7.php(51): Twig\Template->yield(Array, Array)
#15 /var/www/html/craft3/vendor/twig/twig/src/Template.php(393): __TwigTemplate_274bcb2d31df53a06f8ac262a82a617a->doDisplay(Array, Array)
#16 /var/www/html/craft3/vendor/twig/twig/src/Template.php(349): Twig\Template->yield(Array, Array)
#17 /var/www/html/craft3/vendor/twig/twig/src/Template.php(364): Twig\Template->display(Array)
#18 /var/www/html/craft3/vendor/twig/twig/src/TemplateWrapper.php(35): Twig\Template->render(Array)
#19 /var/www/html/craft3/vendor/twig/twig/src/Environment.php(306): Twig\TemplateWrapper->render(Array)
#20 /var/www/html/craft3/vendor/craftcms/cms/src/web/View.php(539): Twig\Environment->render('views/learning-...', Array)
#21 /var/www/html/craft3/vendor/craftcms/cms/src/web/View.php(592): craft\web\View->renderTemplate('views/learning-...', Array)
#22 /var/www/html/craft3/vendor/craftcms/cms/src/web/TemplateResponseFormatter.php(57): craft\web\View->renderPageTemplate('views/learning-...', Array, 'site')
#23 /var/www/html/craft3/vendor/yiisoft/yii2/web/Response.php(1109): craft\web\TemplateResponseFormatter->format(Object(craft\web\Response))
#24 /var/www/html/craft3/vendor/craftcms/cms/src/web/Response.php(339): yii\web\Response->prepare()
#25 /var/www/html/craft3/vendor/yiisoft/yii2/web/Response.php(340): craft\web\Response->prepare()
#26 /var/www/html/craft3/vendor/yiisoft/yii2/base/Application.php(390): yii\web\Response->send()
#27 /var/www/html/craft3/web/index.php(22): yii\base\Application->run()
#28 {main}
```

### Additional info

- Imager version & edition: 5.0.3
- Imager transformer: PDF Adapter 1.1.0
- Craft version: Craft Pro 5.5.3
- PHP version: 8.2.24
- Image driver & version: Imagick 3.7.0 (ImageMagick 6.9.11-60)

**Comment by Christopholus** [comment]
Just chiming in to +1 up this issue. The same problem is affecting the migration of a few of our websites to Craft 5.
