### ISSUE TITLE
PNG not converting to WebP (server issue)

### ISSUE THREAD

**Issue by damonadigital** [spacecatninja/craft-imager-x#281]
### I'm submitting a... 

- [ ] bug report
- [ ] feature request
- [x] general question

### Description
 
After moving my project to a clients desired server environment PNGs no longer convert to WebP. JPG's still convert just fine so it's just a PNG issue. Any thoughts on what server settings could cause this behaviour? See stack trace below

### Displayed errors, stack trace, relevant logs  

```
Imagine\Exception\RuntimeException: An image could not be created from the given input in /home/cumbriagrowthhub/public_html/cumbriagrowthhub/vendor/pixelandtonic/imagine/src/Gd/Imagine.php:213
Stack trace:
#0 /home/cumbriagrowthhub/public_html/cumbriagrowthhub/vendor/pixelandtonic/imagine/src/Gd/Imagine.php(122): Imagine\Gd\Imagine->doLoad('<?xml version="...', Object(Imagine\Image\Metadata\MetadataBag))
#1 /home/cumbriagrowthhub/public_html/cumbriagrowthhub/vendor/craftcms/cms/src/image/Raster.php(605): Imagine\Gd\Imagine->load('<?xml version="...')
#2 /home/cumbriagrowthhub/public_html/cumbriagrowthhub/vendor/craftcms/cms/src/services/Images.php(239): craft\image\Raster->loadFromSVG('<?xml version="...')
#3 /home/cumbriagrowthhub/public_html/cumbriagrowthhub/vendor/craftcms/cms/src/helpers/ImageTransforms.php(426): craft\services\Images->loadImage('/home/cumbriagr...', true, 1200)
#4 /home/cumbriagrowthhub/public_html/cumbriagrowthhub/vendor/craftcms/cms/src/imagetransforms/ImageTransformer.php(376): craft\helpers\ImageTransforms::generateTransform(Object(craft\elements\Asset), Object(craft\models\ImageTransform), Object(Closure), NULL)
#5 /home/cumbriagrowthhub/public_html/cumbriagrowthhub/vendor/craftcms/cms/src/imagetransforms/ImageTransformer.php(462): craft\imagetransforms\ImageTransformer->generateTransformedImage(Object(craft\elements\Asset), Object(craft\models\ImageTransformIndex))
#6 /home/cumbriagrowthhub/public_html/cumbriagrowthhub/vendor/craftcms/cms/src/imagetransforms/ImageTransformer.php(146): craft\imagetransforms\ImageTransformer->generateTransform(Object(craft\models\ImageTransformIndex))
#7 /home/cumbriagrowthhub/public_html/cumbriagrowthhub/vendor/craftcms/cms/src/elements/Asset.php(2242): craft\imagetransforms\ImageTransformer->getTransformUrl(Object(craft\elements\Asset), Object(craft\models\ImageTransform), true)
#8 /home/cumbriagrowthhub/public_html/cumbriagrowthhub/vendor/craftcms/cms/src/elements/Asset.php(2169): craft\elements\Asset->_url(Object(craft\models\ImageTransform), true)
#9 /home/cumbriagrowthhub/public_html/cumbriagrowthhub/vendor/nystudio107/craft-seomatic/src/helpers/ImageTransform.php(151): craft\elements\Asset->getUrl(Object(craft\models\ImageTransform), true)
#10 /home/cumbriagrowthhub/public_html/cumbriagrowthhub/vendor/nystudio107/craft-seomatic/src/services/Helper.php(459): nystudio107\seomatic\helpers\ImageTransform::socialTransform(Object(craft\elements\Asset), 'base', 1, 'crop')
#11 /home/cumbriagrowthhub/public_html/cumbriagrowthhub/vendor/twig/twig/src/Extension/CoreExtension.php(1802): nystudio107\seomatic\services\Helper->socialTransform(1213, 'base', 1, 'crop')
#12 /home/cumbriagrowthhub/public_html/cumbriagrowthhub/vendor/craftcms/cms/src/helpers/Template.php(148): Twig\Extension\CoreExtension::getAttribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(nystudio107\seomatic\services\Helper), 'socialTransform', Array, 'method', false, false, false, 1)
#13 /home/cumbriagrowthhub/public_html/cumbriagrowthhub/storage/runtime/compiled_templates/50/505209e727e915abd91123b31f6c5d3a.php(44): craft\helpers\Template::attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(nystudio107\seomatic\services\Helper), 'socialTransform', Array, 'method', false, false, false, 1)
#14 /home/cumbriagrowthhub/public_html/cumbriagrowthhub/vendor/twig/twig/src/Template.php(393): __TwigTemplate_c5dac559bd434aa672479c0e513cdbca->doDisplay(Array, Array)
#15 /home/cumbriagrowthhub/public_html/cumbriagrowthhub/vendor/twig/twig/src/Template.php(349): Twig\Template->yield(Array, Array)
#16 /home/cumbriagrowthhub/public_html/cumbriagrowthhub/vendor/twig/twig/src/Template.php(364): Twig\Template->display(Array)
#17 /home/cumbriagrowthhub/public_html/cumbriagrowthhub/vendor/twig/twig/src/TemplateWrapper.php(35): Twig\Template->render(Array)
#18 /home/cumbriagrowthhub/public_html/cumbriagrowthhub/vendor/craftcms/cms/src/web/View.php(722): Twig\TemplateWrapper->render(Array)
#19 /home/cumbriagrowthhub/public_html/cumbriagrowthhub/vendor/nystudio107/craft-seomatic/src/helpers/MetaValue.php(276): craft\web\View->renderObjectTemplate('{{ seomatic.hel...', Array, Array)
#20 /home/cumbriagrowthhub/public_html/cumbriagrowthhub/vendor/nystudio107/craft-seomatic/src/helpers/MetaValue.php(102): nystudio107\seomatic\helpers\MetaValue::parseMetaString('{{ seomatic.hel...', true, true)
#21 /home/cumbriagrowthhub/public_html/cumbriagrowthhub/vendor/nystudio107/craft-seomatic/src/helpers/MetaValue.php(149): nystudio107\seomatic\helpers\MetaValue::parseString('{{ seomatic.hel...', true, true, 3)
#22 /home/cumbriagrowthhub/public_html/cumbriagrowthhub/vendor/nystudio107/craft-seomatic/src/services/MetaContainers.php(545): nystudio107\seomatic\helpers\MetaValue::parseArray(Array)
#23 /home/cumbriagrowthhub/public_html/cumbriagrowthhub/vendor/nystudio107/craft-seomatic/src/services/MetaContainers.php(979): nystudio107\seomatic\services\MetaContainers->addMetaBundleToContainers(Object(nystudio107\seomatic\models\MetaBundle))
#24 /home/cumbriagrowthhub/public_html/cumbriagrowthhub/vendor/nystudio107/craft-seomatic/src/services/MetaContainers.php(430): nystudio107\seomatic\services\MetaContainers->loadContentMetaContainers()
#25 /home/cumbriagrowthhub/public_html/cumbriagrowthhub/vendor/nystudio107/craft-seomatic/src/twigextensions/SeomaticTwigExtension.php(54): nystudio107\seomatic\services\MetaContainers->loadMetaContainers('grow-your-busin...', 1)
#26 /home/cumbriagrowthhub/public_html/cumbriagrowthhub/vendor/twig/twig/src/ExtensionSet.php(332): nystudio107\seomatic\twigextensions\SeomaticTwigExtension->getGlobals()
#27 /home/cumbriagrowthhub/public_html/cumbriagrowthhub/vendor/twig/twig/src/Environment.php(824): Twig\ExtensionSet->getGlobals()
#28 /home/cumbriagrowthhub/public_html/cumbriagrowthhub/vendor/twig/twig/src/Template.php(389): Twig\Environment->getGlobals()
#29 /home/cumbriagrowthhub/public_html/cumbriagrowthhub/vendor/twig/twig/src/Template.php(349): Twig\Template->yield(Array, Array)
#30 /home/cumbriagrowthhub/public_html/cumbriagrowthhub/vendor/twig/twig/src/Template.php(364): Twig\Template->display(Array)
#31 /home/cumbriagrowthhub/public_html/cumbriagrowthhub/vendor/twig/twig/src/TemplateWrapper.php(35): Twig\Template->render(Array)
#32 /home/cumbriagrowthhub/public_html/cumbriagrowthhub/vendor/twig/twig/src/Environment.php(306): Twig\TemplateWrapper->render(Array)
#33 /home/cumbriagrowthhub/public_html/cumbriagrowthhub/vendor/craftcms/cms/src/web/View.php(539): Twig\Environment->render('pages/_entry', Array)
#34 /home/cumbriagrowthhub/public_html/cumbriagrowthhub/vendor/craftcms/cms/src/web/View.php(592): craft\web\View->renderTemplate('pages/_entry', Array)
#35 /home/cumbriagrowthhub/public_html/cumbriagrowthhub/vendor/craftcms/cms/src/web/TemplateResponseFormatter.php(57): craft\web\View->renderPageTemplate('pages/_entry', Array, 'site')
#36 /home/cumbriagrowthhub/public_html/cumbriagrowthhub/vendor/yiisoft/yii2/web/Response.php(1109): craft\web\TemplateResponseFormatter->format(Object(craft\web\Response))
#37 /home/cumbriagrowthhub/public_html/cumbriagrowthhub/vendor/craftcms/cms/src/web/Response.php(339): yii\web\Response->prepare()
#38 /home/cumbriagrowthhub/public_html/cumbriagrowthhub/vendor/yiisoft/yii2/web/Response.php(340): craft\web\Response->prepare()
#39 /home/cumbriagrowthhub/public_html/cumbriagrowthhub/vendor/yiisoft/yii2/base/Application.php(390): yii\web\Response->send()
#40 /home/cumbriagrowthhub/public_html/cumbriagrowthhub/public/index.php(12): yii\base\Application->run()
#41 {main}

Next craft\errors\ImageException: Failed to load the SVG string. in /home/cumbriagrowthhub/public_html/cumbriagrowthhub/vendor/craftcms/cms/src/image/Raster.php:607
Stack trace:
#0 /home/cumbriagrowthhub/public_html/cumbriagrowthhub/vendor/craftcms/cms/src/services/Images.php(239): craft\image\Raster->loadFromSVG('<?xml version="...')
#1 /home/cumbriagrowthhub/public_html/cumbriagrowthhub/vendor/craftcms/cms/src/helpers/ImageTransforms.php(426): craft\services\Images->loadImage('/home/cumbriagr...', true, 1200)
#2 /home/cumbriagrowthhub/public_html/cumbriagrowthhub/vendor/craftcms/cms/src/imagetransforms/ImageTransformer.php(376): craft\helpers\ImageTransforms::generateTransform(Object(craft\elements\Asset), Object(craft\models\ImageTransform), Object(Closure), NULL)
#3 /home/cumbriagrowthhub/public_html/cumbriagrowthhub/vendor/craftcms/cms/src/imagetransforms/ImageTransformer.php(462): craft\imagetransforms\ImageTransformer->generateTransformedImage(Object(craft\elements\Asset), Object(craft\models\ImageTransformIndex))
#4 /home/cumbriagrowthhub/public_html/cumbriagrowthhub/vendor/craftcms/cms/src/imagetransforms/ImageTransformer.php(146): craft\imagetransforms\ImageTransformer->generateTransform(Object(craft\models\ImageTransformIndex))
#5 /home/cumbriagrowthhub/public_html/cumbriagrowthhub/vendor/craftcms/cms/src/elements/Asset.php(2242): craft\imagetransforms\ImageTransformer->getTransformUrl(Object(craft\elements\Asset), Object(craft\models\ImageTransform), true)
#6 /home/cumbriagrowthhub/public_html/cumbriagrowthhub/vendor/craftcms/cms/src/elements/Asset.php(2169): craft\elements\Asset->_url(Object(craft\models\ImageTransform), true)
#7 /home/cumbriagrowthhub/public_html/cumbriagrowthhub/vendor/nystudio107/craft-seomatic/src/helpers/ImageTransform.php(151): craft\elements\Asset->getUrl(Object(craft\models\ImageTransform), true)
#8 /home/cumbriagrowthhub/public_html/cumbriagrowthhub/vendor/nystudio107/craft-seomatic/src/services/Helper.php(459): nystudio107\seomatic\helpers\ImageTransform::socialTransform(Object(craft\elements\Asset), 'base', 1, 'crop')
#9 /home/cumbriagrowthhub/public_html/cumbriagrowthhub/vendor/twig/twig/src/Extension/CoreExtension.php(1802): nystudio107\seomatic\services\Helper->socialTransform(1213, 'base', 1, 'crop')
#10 /home/cumbriagrowthhub/public_html/cumbriagrowthhub/vendor/craftcms/cms/src/helpers/Template.php(148): Twig\Extension\CoreExtension::getAttribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(nystudio107\seomatic\services\Helper), 'socialTransform', Array, 'method', false, false, false, 1)
#11 /home/cumbriagrowthhub/public_html/cumbriagrowthhub/storage/runtime/compiled_templates/50/505209e727e915abd91123b31f6c5d3a.php(44): craft\helpers\Template::attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(nystudio107\seomatic\services\Helper), 'socialTransform', Array, 'method', false, false, false, 1)
#12 /home/cumbriagrowthhub/public_html/cumbriagrowthhub/vendor/twig/twig/src/Template.php(393): __TwigTemplate_c5dac559bd434aa672479c0e513cdbca->doDisplay(Array, Array)
#13 /home/cumbriagrowthhub/public_html/cumbriagrowthhub/vendor/twig/twig/src/Template.php(349): Twig\Template->yield(Array, Array)
#14 /home/cumbriagrowthhub/public_html/cumbriagrowthhub/vendor/twig/twig/src/Template.php(364): Twig\Template->display(Array)
#15 /home/cumbriagrowthhub/public_html/cumbriagrowthhub/vendor/twig/twig/src/TemplateWrapper.php(35): Twig\Template->render(Array)
#16 /home/cumbriagrowthhub/public_html/cumbriagrowthhub/vendor/craftcms/cms/src/web/View.php(722): Twig\TemplateWrapper->render(Array)
#17 /home/cumbriagrowthhub/public_html/cumbriagrowthhub/vendor/nystudio107/craft-seomatic/src/helpers/MetaValue.php(276): craft\web\View->renderObjectTemplate('{{ seomatic.hel...', Array, Array)
#18 /home/cumbriagrowthhub/public_html/cumbriagrowthhub/vendor/nystudio107/craft-seomatic/src/helpers/MetaValue.php(102): nystudio107\seomatic\helpers\MetaValue::parseMetaString('{{ seomatic.hel...', true, true)
#19 /home/cumbriagrowthhub/public_html/cumbriagrowthhub/vendor/nystudio107/craft-seomatic/src/helpers/MetaValue.php(149): nystudio107\seomatic\helpers\MetaValue::parseString('{{ seomatic.hel...', true, true, 3)
#20 /home/cumbriagrowthhub/public_html/cumbriagrowthhub/vendor/nystudio107/craft-seomatic/src/services/MetaContainers.php(545): nystudio107\seomatic\helpers\MetaValue::parseArray(Array)
#21 /home/cumbriagrowthhub/public_html/cumbriagrowthhub/vendor/nystudio107/craft-seomatic/src/services/MetaContainers.php(979): nystudio107\seomatic\services\MetaContainers->addMetaBundleToContainers(Object(nystudio107\seomatic\models\MetaBundle))
#22 /home/cumbriagrowthhub/public_html/cumbriagrowthhub/vendor/nystudio107/craft-seomatic/src/services/MetaContainers.php(430): nystudio107\seomatic\services\MetaContainers->loadContentMetaContainers()
#23 /home/cumbriagrowthhub/public_html/cumbriagrowthhub/vendor/nystudio107/craft-seomatic/src/twigextensions/SeomaticTwigExtension.php(54): nystudio107\seomatic\services\MetaContainers->loadMetaContainers('grow-your-busin...', 1)
#24 /home/cumbriagrowthhub/public_html/cumbriagrowthhub/vendor/twig/twig/src/ExtensionSet.php(332): nystudio107\seomatic\twigextensions\SeomaticTwigExtension->getGlobals()
#25 /home/cumbriagrowthhub/public_html/cumbriagrowthhub/vendor/twig/twig/src/Environment.php(824): Twig\ExtensionSet->getGlobals()
#26 /home/cumbriagrowthhub/public_html/cumbriagrowthhub/vendor/twig/twig/src/Template.php(389): Twig\Environment->getGlobals()
#27 /home/cumbriagrowthhub/public_html/cumbriagrowthhub/vendor/twig/twig/src/Template.php(349): Twig\Template->yield(Array, Array)
#28 /home/cumbriagrowthhub/public_html/cumbriagrowthhub/vendor/twig/twig/src/Template.php(364): Twig\Template->display(Array)
#29 /home/cumbriagrowthhub/public_html/cumbriagrowthhub/vendor/twig/twig/src/TemplateWrapper.php(35): Twig\Template->render(Array)
#30 /home/cumbriagrowthhub/public_html/cumbriagrowthhub/vendor/twig/twig/src/Environment.php(306): Twig\TemplateWrapper->render(Array)
#31 /home/cumbriagrowthhub/public_html/cumbriagrowthhub/vendor/craftcms/cms/src/web/View.php(539): Twig\Environment->render('pages/_entry', Array)
#32 /home/cumbriagrowthhub/public_html/cumbriagrowthhub/vendor/craftcms/cms/src/web/View.php(592): craft\web\View->renderTemplate('pages/_entry', Array)
#33 /home/cumbriagrowthhub/public_html/cumbriagrowthhub/vendor/craftcms/cms/src/web/TemplateResponseFormatter.php(57): craft\web\View->renderPageTemplate('pages/_entry', Array, 'site')
#34 /home/cumbriagrowthhub/public_html/cumbriagrowthhub/vendor/yiisoft/yii2/web/Response.php(1109): craft\web\TemplateResponseFormatter->format(Object(craft\web\Response))
#35 /home/cumbriagrowthhub/public_html/cumbriagrowthhub/vendor/craftcms/cms/src/web/Response.php(339): yii\web\Response->prepare()
#36 /home/cumbriagrowthhub/public_html/cumbriagrowthhub/vendor/yiisoft/yii2/web/Response.php(340): craft\web\Response->prepare()
#37 /home/cumbriagrowthhub/public_html/cumbriagrowthhub/vendor/yiisoft/yii2/base/Application.php(390): yii\web\Response->send()
#38 /home/cumbriagrowthhub/public_html/cumbriagrowthhub/public/index.php(12): yii\base\Application->run()
#39 {main}

Next craft\errors\ImageTransformException: Failed to generate transform with id of 1. in /home/cumbriagrowthhub/public_html/cumbriagrowthhub/vendor/craftcms/cms/src/imagetransforms/ImageTransformer.php:153
Stack trace:
#0 /home/cumbriagrowthhub/public_html/cumbriagrowthhub/vendor/craftcms/cms/src/elements/Asset.php(2242): craft\imagetransforms\ImageTransformer->getTransformUrl(Object(craft\elements\Asset), Object(craft\models\ImageTransform), true)
#1 /home/cumbriagrowthhub/public_html/cumbriagrowthhub/vendor/craftcms/cms/src/elements/Asset.php(2169): craft\elements\Asset->_url(Object(craft\models\ImageTransform), true)
#2 /home/cumbriagrowthhub/public_html/cumbriagrowthhub/vendor/nystudio107/craft-seomatic/src/helpers/ImageTransform.php(151): craft\elements\Asset->getUrl(Object(craft\models\ImageTransform), true)
#3 /home/cumbriagrowthhub/public_html/cumbriagrowthhub/vendor/nystudio107/craft-seomatic/src/services/Helper.php(459): nystudio107\seomatic\helpers\ImageTransform::socialTransform(Object(craft\elements\Asset), 'base', 1, 'crop')
#4 /home/cumbriagrowthhub/public_html/cumbriagrowthhub/vendor/twig/twig/src/Extension/CoreExtension.php(1802): nystudio107\seomatic\services\Helper->socialTransform(1213, 'base', 1, 'crop')
#5 /home/cumbriagrowthhub/public_html/cumbriagrowthhub/vendor/craftcms/cms/src/helpers/Template.php(148): Twig\Extension\CoreExtension::getAttribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(nystudio107\seomatic\services\Helper), 'socialTransform', Array, 'method', false, false, false, 1)
#6 /home/cumbriagrowthhub/public_html/cumbriagrowthhub/storage/runtime/compiled_templates/50/505209e727e915abd91123b31f6c5d3a.php(44): craft\helpers\Template::attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(nystudio107\seomatic\services\Helper), 'socialTransform', Array, 'method', false, false, false, 1)
#7 /home/cumbriagrowthhub/public_html/cumbriagrowthhub/vendor/twig/twig/src/Template.php(393): __TwigTemplate_c5dac559bd434aa672479c0e513cdbca->doDisplay(Array, Array)
#8 /home/cumbriagrowthhub/public_html/cumbriagrowthhub/vendor/twig/twig/src/Template.php(349): Twig\Template->yield(Array, Array)
#9 /home/cumbriagrowthhub/public_html/cumbriagrowthhub/vendor/twig/twig/src/Template.php(364): Twig\Template->display(Array)
#10 /home/cumbriagrowthhub/public_html/cumbriagrowthhub/vendor/twig/twig/src/TemplateWrapper.php(35): Twig\Template->render(Array)
#11 /home/cumbriagrowthhub/public_html/cumbriagrowthhub/vendor/craftcms/cms/src/web/View.php(722): Twig\TemplateWrapper->render(Array)
#12 /home/cumbriagrowthhub/public_html/cumbriagrowthhub/vendor/nystudio107/craft-seomatic/src/helpers/MetaValue.php(276): craft\web\View->renderObjectTemplate('{{ seomatic.hel...', Array, Array)
#13 /home/cumbriagrowthhub/public_html/cumbriagrowthhub/vendor/nystudio107/craft-seomatic/src/helpers/MetaValue.php(102): nystudio107\seomatic\helpers\MetaValue::parseMetaString('{{ seomatic.hel...', true, true)
#14 /home/cumbriagrowthhub/public_html/cumbriagrowthhub/vendor/nystudio107/craft-seomatic/src/helpers/MetaValue.php(149): nystudio107\seomatic\helpers\MetaValue::parseString('{{ seomatic.hel...', true, true, 3)
#15 /home/cumbriagrowthhub/public_html/cumbriagrowthhub/vendor/nystudio107/craft-seomatic/src/services/MetaContainers.php(545): nystudio107\seomatic\helpers\MetaValue::parseArray(Array)
#16 /home/cumbriagrowthhub/public_html/cumbriagrowthhub/vendor/nystudio107/craft-seomatic/src/services/MetaContainers.php(979): nystudio107\seomatic\services\MetaContainers->addMetaBundleToContainers(Object(nystudio107\seomatic\models\MetaBundle))
#17 /home/cumbriagrowthhub/public_html/cumbriagrowthhub/vendor/nystudio107/craft-seomatic/src/services/MetaContainers.php(430): nystudio107\seomatic\services\MetaContainers->loadContentMetaContainers()
#18 /home/cumbriagrowthhub/public_html/cumbriagrowthhub/vendor/nystudio107/craft-seomatic/src/twigextensions/SeomaticTwigExtension.php(54): nystudio107\seomatic\services\MetaContainers->loadMetaContainers('grow-your-busin...', 1)
#19 /home/cumbriagrowthhub/public_html/cumbriagrowthhub/vendor/twig/twig/src/ExtensionSet.php(332): nystudio107\seomatic\twigextensions\SeomaticTwigExtension->getGlobals()
#20 /home/cumbriagrowthhub/public_html/cumbriagrowthhub/vendor/twig/twig/src/Environment.php(824): Twig\ExtensionSet->getGlobals()
#21 /home/cumbriagrowthhub/public_html/cumbriagrowthhub/vendor/twig/twig/src/Template.php(389): Twig\Environment->getGlobals()
#22 /home/cumbriagrowthhub/public_html/cumbriagrowthhub/vendor/twig/twig/src/Template.php(349): Twig\Template->yield(Array, Array)
#23 /home/cumbriagrowthhub/public_html/cumbriagrowthhub/vendor/twig/twig/src/Template.php(364): Twig\Template->display(Array)
#24 /home/cumbriagrowthhub/public_html/cumbriagrowthhub/vendor/twig/twig/src/TemplateWrapper.php(35): Twig\Template->render(Array)
#25 /home/cumbriagrowthhub/public_html/cumbriagrowthhub/vendor/twig/twig/src/Environment.php(306): Twig\TemplateWrapper->render(Array)
#26 /home/cumbriagrowthhub/public_html/cumbriagrowthhub/vendor/craftcms/cms/src/web/View.php(539): Twig\Environment->render('pages/_entry', Array)
#27 /home/cumbriagrowthhub/public_html/cumbriagrowthhub/vendor/craftcms/cms/src/web/View.php(592): craft\web\View->renderTemplate('pages/_entry', Array)
#28 /home/cumbriagrowthhub/public_html/cumbriagrowthhub/vendor/craftcms/cms/src/web/TemplateResponseFormatter.php(57): craft\web\View->renderPageTemplate('pages/_entry', Array, 'site')
#29 /home/cumbriagrowthhub/public_html/cumbriagrowthhub/vendor/yiisoft/yii2/web/Response.php(1109): craft\web\TemplateResponseFormatter->format(Object(craft\web\Response))
#30 /home/cumbriagrowthhub/public_html/cumbriagrowthhub/vendor/craftcms/cms/src/web/Response.php(339): yii\web\Response->prepare()
#31 /home/cumbriagrowthhub/public_html/cumbriagrowthhub/vendor/yiisoft/yii2/web/Response.php(340): craft\web\Response->prepare()
#32 /home/cumbriagrowthhub/public_html/cumbriagrowthhub/vendor/yiisoft/yii2/base/Application.php(390): yii\web\Response->send()
#33 /home/cumbriagrowthhub/public_html/cumbriagrowthhub/public/index.php(12): yii\base\Application->run()
#34 {main}
```

### Additional info

- Imager version & edition: 5.0.3
- Imager transformer: Default
- Craft version: Craft Pro 5.5.3
- PHP version: 8.2.26
- Image driver & version: GD 8.2.26

**Comment by aelvan** [comment]
Hi,

When do you get this error? From what I can tell, Imager isn't involved in the stack trace at all. And from the looks of it, the file being loaded is a SVG file?

**Comment by damonadigital** [comment]
Hi Aelvan, 

I believe you are correct this trace is unrelated to Imager and the issue described. I did manage to solve the issue, turns out it was due to caching that I hadn't noticed.

Thanks for your follow up questions.
