### ISSUE TITLE
Seeing exceptions

### ISSUE THREAD

**Issue by bossanova808** [spacecatninja/craft-imager-x#35]
### I'm submitting a... 

- [ ] bug report
- [ ] feature request
- [x] general question

### Description

Seeing periodic errors in our Rollbar logs:
```
An exception has been thrown during the rendering of a template ("unlink(/srv/users/serverpilot/apps/imagescience/releases/dev/storage/runtime/imager/s3images/Knowledge-Base/Colour-Accurate-Monitors/Calibrate-an-Eizo-Using-ColorNavigator-V7/52424/~Color-Navigator-7-Actually-Calibrate.jpg): No such file or directory").
```

I'm not seeing a functional issue, the [entry in question](https://imagescience.com.au/knowledge/how-to-calibrate-an-eizo-coloredge-monitor-using-colornavigator) loads just fine.

I just don't like seeing exceptions in my logs.   ;)

Just raising it as an FYI more than anything...if it is expected that such files might not be there, then perhaps it shoudn't raise the exception.  On the other hand, if they are missing, and shouldn't be....I guess I'd like to know why!

(Hope you're well - Imager-X is awesome :) )

### Additional info

All versions latest as of this morning.

**Comment by aelvan** [comment]
Hi Jeremy!

I don't like exceptions either! :) Could you post more of the stack trace so I can see exactly where it happens? Also, do you have any other errors in your logs that could be related to this?

**Comment by bossanova808** [comment]
So I can't find anything else related, but here's the trace from `web.log`

```
2020-07-01 00:30:54 [-][-][7ef27cc54d4130868469c342bc93acd6][error][yii\base\ErrorException:2] yii\base\ErrorException: unlink(/srv/users/serverpilot/apps/imagescience/releases/dev/storage/runtime/imager/s3images/Blog-Articles/2018/Christmas-Print-Giveaway/44831/~Rachel-Urquhart-Wade-2018.jpg): No such file or directory in /srv/users/serverpilot/apps/imagescience/releases/dev/vendor/spacecatninja/imager-x/src/models/LocalSourceImageModel.php:163
Stack trace:
#0 /srv/users/serverpilot/apps/imagescience/releases/dev/vendor/craftcms/cms/src/web/ErrorHandler.php(74): yii\base\ErrorHandler->handleError(2, 'unlink(/srv/use...', '/srv/users/serv...', 163)
#1 [internal function]: craft\web\ErrorHandler->handleError(2, 'unlink(/srv/use...', '/srv/users/serv...', 163, Array)
#2 /srv/users/serverpilot/apps/imagescience/releases/dev/vendor/spacecatninja/imager-x/src/models/LocalSourceImageModel.php(163): unlink('/srv/users/serv...')
#3 /srv/users/serverpilot/apps/imagescience/releases/dev/vendor/spacecatninja/imager-x/src/transformers/CraftTransformer.php(157): spacecatninja\imagerx\models\LocalSourceImageModel->getLocalCopy()
#4 /srv/users/serverpilot/apps/imagescience/releases/dev/vendor/spacecatninja/imager-x/src/transformers/CraftTransformer.php(96): spacecatninja\imagerx\transformers\CraftTransformer->getTransformedImage(Object(spacecatninja\imagerx\models\LocalSourceImageModel), Array)
#5 /srv/users/serverpilot/apps/imagescience/releases/dev/vendor/spacecatninja/imager-x/src/services/ImagerService.php(421): spacecatninja\imagerx\transformers\CraftTransformer->transform(Object(craft\elements\Asset), Array)
#6 /srv/users/serverpilot/apps/imagescience/releases/dev/vendor/spacecatninja/imager-x/src/variables/ImagerVariable.php(37): spacecatninja\imagerx\services\ImagerService->transformImage(Object(craft\elements\Asset), Array, Array, Array)
#7 /srv/users/serverpilot/apps/imagescience/releases/dev/vendor/twig/twig/src/Extension/CoreExtension.php(1499): spacecatninja\imagerx\variables\ImagerVariable->transformImage(Object(craft\elements\Asset), 'square500')
#8 /srv/users/serverpilot/apps/imagescience/releases/dev/vendor/craftcms/cms/src/helpers/Template.php(96): twig_get_attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(spacecatninja\imagerx\variables\ImagerVariable), 'transformImage', Array, 'method', false, false)
#9 /srv/users/serverpilot/apps/imagescience/releases/dev/storage/runtime/compiled_templates/15/15aaf19c011328d67aa13c2b7d522f912d9ade6e7d93792a291d73bd37808d89.php(145): craft\helpers\Template::attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(spacecatninja\imagerx\variables\ImagerVariable), 'transformImage', Array, 'method')
#10 /srv/users/serverpilot/apps/imagescience/releases/dev/vendor/twig/twig/src/Extension/CoreExtension.php(1109): __TwigTemplate_c7fca5b9e440f5c1183180eccec3dd8e1526f3dfbe19f6fe16d52aca47e345e1->macro_srcset(Array)
#11 /srv/users/serverpilot/apps/imagescience/releases/dev/storage/runtime/compiled_templates/dd/dde95d83448a4469b2af88b190d3ae90905b273b89cb19ea7c84510fb7f702a4.php(317): twig_call_macro(Object(__TwigTemplate_c7fca5b9e440f5c1183180eccec3dd8e1526f3dfbe19f6fe16d52aca47e345e1), 'macro_srcset', Array, 132, Array, Object(Twig\Source))
#12 /srv/users/serverpilot/apps/imagescience/releases/dev/vendor/twig/twig/src/Template.php(184): __TwigTemplate_cb9f28c31128f6c2d3a535300045f646ac05976853f5e1488145552406f6bf01___1017267971->block_leftColumn(Array, Array)
#13 /srv/users/serverpilot/apps/imagescience/releases/dev/storage/runtime/compiled_templates/46/46a91c2982aea6f21c54db7be9cc0bb60c5a69ecd03b64e76513a658dfe31c15.php(84): Twig\Template->displayBlock('leftColumn', Array, Array)
#14 /srv/users/serverpilot/apps/imagescience/releases/dev/vendor/twig/twig/src/Template.php(184): __TwigTemplate_2471139f0f278e0ee582c404888e902c0ca36ffdbf4129912c78bdbb66d63acb->block_structure(Array, Array)
#15 /srv/users/serverpilot/apps/imagescience/releases/dev/storage/runtime/compiled_templates/46/46a91c2982aea6f21c54db7be9cc0bb60c5a69ecd03b64e76513a658dfe31c15.php(47): Twig\Template->displayBlock('structure', Array, Array)
#16 /srv/users/serverpilot/apps/imagescience/releases/dev/vendor/twig/twig/src/Template.php(407): __TwigTemplate_2471139f0f278e0ee582c404888e902c0ca36ffdbf4129912c78bdbb66d63acb->doDisplay(Array, Array)
#17 /srv/users/serverpilot/apps/imagescience/releases/dev/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#18 /srv/users/serverpilot/apps/imagescience/releases/dev/storage/runtime/compiled_templates/dd/dde95d83448a4469b2af88b190d3ae90905b273b89cb19ea7c84510fb7f702a4.php(239): Twig\Template->display(Array, Array)
#19 /srv/users/serverpilot/apps/imagescience/releases/dev/vendor/twig/twig/src/Template.php(407): __TwigTemplate_cb9f28c31128f6c2d3a535300045f646ac05976853f5e1488145552406f6bf01___1017267971->doDisplay(Array, Array)
#20 /srv/users/serverpilot/apps/imagescience/releases/dev/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#21 /srv/users/serverpilot/apps/imagescience/releases/dev/storage/runtime/compiled_templates/dd/dde95d83448a4469b2af88b190d3ae90905b273b89cb19ea7c84510fb7f702a4.php(172): Twig\Template->display(Array)
#22 /srv/users/serverpilot/apps/imagescience/releases/dev/vendor/twig/twig/src/Template.php(184): __TwigTemplate_cb9f28c31128f6c2d3a535300045f646ac05976853f5e1488145552406f6bf01->block_structure(Array, Array)
#23 /srv/users/serverpilot/apps/imagescience/releases/dev/storage/runtime/compiled_templates/0f/0fe1060329fca99b8a9c0e406a7ef3dd6e3ca28d09aa326679d02c4d8c908799.php(241): Twig\Template->displayBlock('structure', Array, Array)
#24 /srv/users/serverpilot/apps/imagescience/releases/dev/vendor/twig/twig/src/Template.php(407): __TwigTemplate_e0f5d2e63426070931cfb1aaa44d07a18756859cc34b3bf0daa95b95e6769d46->doDisplay(Array, Array)
#25 /srv/users/serverpilot/apps/imagescience/releases/dev/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#26 /srv/users/serverpilot/apps/imagescience/releases/dev/storage/runtime/compiled_templates/dd/dde95d83448a4469b2af88b190d3ae90905b273b89cb19ea7c84510fb7f702a4.php(152): Twig\Template->display(Array, Array)
#27 /srv/users/serverpilot/apps/imagescience/releases/dev/vendor/twig/twig/src/Template.php(407): __TwigTemplate_cb9f28c31128f6c2d3a535300045f646ac05976853f5e1488145552406f6bf01->doDisplay(Array, Array)
#28 /srv/users/serverpilot/apps/imagescience/releases/dev/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#29 /srv/users/serverpilot/apps/imagescience/releases/dev/vendor/twig/twig/src/Template.php(392): Twig\Template->display(Array)
#30 /srv/users/serverpilot/apps/imagescience/releases/dev/vendor/twig/twig/src/TemplateWrapper.php(45): Twig\Template->render(Array, Array)
#31 /srv/users/serverpilot/apps/imagescience/releases/dev/vendor/twig/twig/src/Environment.php(318): Twig\TemplateWrapper->render(Array)
#32 /srv/users/serverpilot/apps/imagescience/releases/dev/vendor/craftcms/cms/src/web/View.php(375): Twig\Environment->render('blog/index', Array)
#33 /srv/users/serverpilot/apps/imagescience/releases/dev/vendor/craftcms/cms/src/web/View.php(436): craft\web\View->renderTemplate('blog/index', Array)
#34 /srv/users/serverpilot/apps/imagescience/releases/dev/vendor/craftcms/cms/src/web/Controller.php(235): craft\web\View->renderPageTemplate('blog/index', Array, 'site')
#35 /srv/users/serverpilot/apps/imagescience/releases/dev/vendor/craftcms/cms/src/controllers/TemplatesController.php(98): craft\web\Controller->renderTemplate('blog/index', Array)
#36 [internal function]: craft\controllers\TemplatesController->actionRender('blog/index', Array)
#37 /srv/users/serverpilot/apps/imagescience/releases/dev/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#38 /srv/users/serverpilot/apps/imagescience/releases/dev/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#39 /srv/users/serverpilot/apps/imagescience/releases/dev/vendor/craftcms/cms/src/web/Controller.php(178): yii\base\Controller->runAction('render', Array)
#40 /srv/users/serverpilot/apps/imagescience/releases/dev/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('render', Array)
#41 /srv/users/serverpilot/apps/imagescience/releases/dev/vendor/craftcms/cms/src/web/Application.php(291): yii\base\Module->runAction('templates/rende...', Array)
#42 /srv/users/serverpilot/apps/imagescience/releases/dev/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('templates/rende...', Array)
#43 /srv/users/serverpilot/apps/imagescience/releases/dev/vendor/craftcms/cms/src/web/Application.php(276): yii\web\Application->handleRequest(Object(craft\web\Request))
#44 /srv/users/serverpilot/apps/imagescience/releases/dev/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#45 /srv/users/serverpilot/apps/imagescience/releases/dev/web/index.php(21): yii\base\Application->run()
#46 {main}
2020-07-01 00:30:50 [-][-][7ef27cc54d4130868469c342bc93acd6][info][application] $_GET = [
    'p' => 'blog/category/general-articles'
```

**Comment by bossanova808** [comment]
...and sorry, should have dug up the whole thing before this.  On rollbar we just get the one line, though, so I was lazy ;)

**Comment by aelvan** [comment]
Thanks, that's helpful. You said "periodic errors", how often is that? 

Nothing seriously wrong going on there, it's _probably_ just a race condition where two separate processes are downloading the same external file at the same time, and then the temporary file has already been removed before the  second process finished. I'll silence the error in the next release.

**Comment by bossanova808** [comment]
A few times a week maybe?  

Thanks for looking at it!
