### ISSUE TITLE
Craft 3.5 Undefined index: extension

### ISSUE THREAD

**Issue by faradaytrs** [spacecatninja/craft-imager-x#41]
### I'm submitting a... 

- [x] bug report
- [ ] feature request
- [ ] general question

### Steps to reproduce

1. Upgrade for craft 3.5
2. get error
3. ...

### Description
 
PHP Notice – yii\base\ErrorException
Undefined index: extension

### Displayed errors, stack trace, relevant logs  

```
yii\base\ErrorException: Undefined index: extension in /Users/imax/PhpstormProjects/globus/vendor/spacecatninja/imager-x/src/models/LocalSourceImageModel.php:283
Stack trace:
#0 /Users/imax/PhpstormProjects/globus/vendor/craftcms/cms/src/web/ErrorHandler.php(75): yii\base\ErrorHandler->handleError(8, 'Undefined index...', '/Users/imax/Php...', 283)
#1 /Users/imax/PhpstormProjects/globus/vendor/spacecatninja/imager-x/src/models/LocalSourceImageModel.php(283): craft\web\ErrorHandler->handleError(8, 'Undefined index...', '/Users/imax/Php...', 283, Array)
#2 /Users/imax/PhpstormProjects/globus/vendor/spacecatninja/imager-x/src/models/LocalSourceImageModel.php(91): spacecatninja\imagerx\models\LocalSourceImageModel->getPathsForLocalFile('Synced sequence...')
#3 /Users/imax/PhpstormProjects/globus/vendor/spacecatninja/imager-x/src/models/LocalSourceImageModel.php(60): spacecatninja\imagerx\models\LocalSourceImageModel->init('Synced sequence...')
#4 /Users/imax/PhpstormProjects/globus/vendor/spacecatninja/imager-x/src/transformers/CraftTransformer.php(86): spacecatninja\imagerx\models\LocalSourceImageModel->__construct('Synced sequence...')
#5 /Users/imax/PhpstormProjects/globus/vendor/spacecatninja/imager-x/src/services/ImagerService.php(421): spacecatninja\imagerx\transformers\CraftTransformer->transform('Synced sequence...', Array)
#6 /Users/imax/PhpstormProjects/globus/vendor/spacecatninja/imager-x/src/variables/ImagerVariable.php(37): spacecatninja\imagerx\services\ImagerService->transformImage('Synced sequence...', Array, Array, NULL)
#7 /Users/imax/PhpstormProjects/globus/vendor/twig/twig/src/Extension/CoreExtension.php(1499): spacecatninja\imagerx\variables\ImagerVariable->transformImage('Synced sequence...', Array, Array)
#8 /Users/imax/PhpstormProjects/globus/vendor/craftcms/cms/src/helpers/Template.php(90): twig_get_attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(spacecatninja\imagerx\variables\ImagerVariable), 'transformImage', Array, 'method', false, false)
#9 /Users/imax/PhpstormProjects/globus/storage/runtime/compiled_templates/f8/f89ad95146a0c0ce76d9242f321e09228243d586a1fbb21d556798c431199ce6.php(52): craft\helpers\Template::attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(spacecatninja\imagerx\variables\ImagerVariable), 'transformImage', Array, 'method')
#10 /Users/imax/PhpstormProjects/globus/vendor/twig/twig/src/Template.php(407): __TwigTemplate_dc67532f8051680e265fc69a9456c33136fa8084474557d2abf1e738b3fadfd7->doDisplay(Array, Array)
#11 /Users/imax/PhpstormProjects/globus/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#12 /Users/imax/PhpstormProjects/globus/storage/runtime/compiled_templates/03/03b02753b5b5e9a06ee53475ff3fabf3c4130f869d5a35b66a554ba72b619201.php(78): Twig\Template->display(Array)
#13 /Users/imax/PhpstormProjects/globus/vendor/twig/twig/src/Template.php(407): __TwigTemplate_d57a6420bf9eac9d8216bdb75e6d4174af01ab3eba08d48deb50d37f1c36c4cb->doDisplay(Array, Array)
#14 /Users/imax/PhpstormProjects/globus/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#15 /Users/imax/PhpstormProjects/globus/storage/runtime/compiled_templates/ba/baadf84b4368e876cd8c566de6a691951e462803ae2534f4b0617e952cde7e28.php(75): Twig\Template->display(Array)
#16 /Users/imax/PhpstormProjects/globus/vendor/twig/twig/src/Template.php(407): __TwigTemplate_8c2b79a6759667fee3353e19524f3a4a4e1944a7962ef07a4aaeb3f6622c289e->doDisplay(Array, Array)
#17 /Users/imax/PhpstormProjects/globus/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#18 /Users/imax/PhpstormProjects/globus/storage/runtime/compiled_templates/a4/a447082596d8e3f05466d6277ab82529aea66f081edc555a94a14a4fb721e9c6.php(95): Twig\Template->display(Array)
#19 /Users/imax/PhpstormProjects/globus/vendor/twig/twig/src/Template.php(184): __TwigTemplate_ff3b7c9d9fcfac441720b073b3d0f6754561b4b4c6b21899cbdd4c459838c40a->block_content(Array, Array)
#20 /Users/imax/PhpstormProjects/globus/storage/runtime/compiled_templates/dc/dc82d70df0802a5dfc7b5de6432a83297d2561bb3f82bd6b4f37a6e12158ebd6.php(88): Twig\Template->displayBlock('content', Array, Array)
#21 /Users/imax/PhpstormProjects/globus/vendor/twig/twig/src/Template.php(184): __TwigTemplate_03b4571192c216d349a1e6170e49ec563c158cb3451482a52e1a492b60b9c75d->block_body(Array, Array)
#22 /Users/imax/PhpstormProjects/globus/storage/runtime/compiled_templates/f3/f3f3ac75728e5e4a6f61afe8556aa68465efd66ee446906ad60e5df18359df19.php(66): Twig\Template->displayBlock('body', Array, Array)
#23 /Users/imax/PhpstormProjects/globus/vendor/twig/twig/src/Template.php(407): __TwigTemplate_b37abe53ec71b583892dc021e924115e30207793dcd1e7c9a33511f22d478273->doDisplay(Array, Array)
#24 /Users/imax/PhpstormProjects/globus/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#25 /Users/imax/PhpstormProjects/globus/storage/runtime/compiled_templates/dc/dc82d70df0802a5dfc7b5de6432a83297d2561bb3f82bd6b4f37a6e12158ebd6.php(46): Twig\Template->display(Array, Array)
#26 /Users/imax/PhpstormProjects/globus/vendor/twig/twig/src/Template.php(407): __TwigTemplate_03b4571192c216d349a1e6170e49ec563c158cb3451482a52e1a492b60b9c75d->doDisplay(Array, Array)
#27 /Users/imax/PhpstormProjects/globus/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#28 /Users/imax/PhpstormProjects/globus/storage/runtime/compiled_templates/a4/a447082596d8e3f05466d6277ab82529aea66f081edc555a94a14a4fb721e9c6.php(63): Twig\Template->display(Array, Array)
#29 /Users/imax/PhpstormProjects/globus/vendor/twig/twig/src/Template.php(407): __TwigTemplate_ff3b7c9d9fcfac441720b073b3d0f6754561b4b4c6b21899cbdd4c459838c40a->doDisplay(Array, Array)
#30 /Users/imax/PhpstormProjects/globus/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#31 /Users/imax/PhpstormProjects/globus/vendor/twig/twig/src/Template.php(392): Twig\Template->display(Array)
#32 /Users/imax/PhpstormProjects/globus/vendor/twig/twig/src/TemplateWrapper.php(45): Twig\Template->render(Array, Array)
#33 /Users/imax/PhpstormProjects/globus/vendor/twig/twig/src/Environment.php(318): Twig\TemplateWrapper->render(Array)
#34 /Users/imax/PhpstormProjects/globus/vendor/craftcms/cms/src/web/View.php(391): Twig\Environment->render('_index', Array)
#35 /Users/imax/PhpstormProjects/globus/vendor/craftcms/cms/src/web/View.php(452): craft\web\View->renderTemplate('_index', Array)
#36 /Users/imax/PhpstormProjects/globus/vendor/craftcms/cms/src/web/Controller.php(243): craft\web\View->renderPageTemplate('_index', Array, 'site')
#37 /Users/imax/PhpstormProjects/globus/vendor/craftcms/cms/src/controllers/TemplatesController.php(97): craft\web\Controller->renderTemplate('_index', Array)
#38 [internal function]: craft\controllers\TemplatesController->actionRender('_index', Array)
#39 /Users/imax/PhpstormProjects/globus/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#40 /Users/imax/PhpstormProjects/globus/vendor/yiisoft/yii2/base/Controller.php(180): yii\base\InlineAction->runWithParams(Array)
#41 /Users/imax/PhpstormProjects/globus/vendor/craftcms/cms/src/web/Controller.php(181): yii\base\Controller->runAction('render', Array)
#42 /Users/imax/PhpstormProjects/globus/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('render', Array)
#43 /Users/imax/PhpstormProjects/globus/vendor/craftcms/cms/src/web/Application.php(294): yii\base\Module->runAction('templates/rende...', Array)
#44 /Users/imax/PhpstormProjects/globus/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('templates/rende...', Array)
#45 /Users/imax/PhpstormProjects/globus/vendor/craftcms/cms/src/web/Application.php(279): yii\web\Application->handleRequest(Object(craft\web\Request))
#46 /Users/imax/PhpstormProjects/globus/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#47 /Users/imax/PhpstormProjects/globus/web/index.php(21): yii\base\Application->run()
#48 {main}
```

### Additional info

Imagex-X trial lite
PHP version | 7.4.8
-- | --
Darwin  | 19.6.0
MySQL |  5.5.5
GD  | 7.4.8
Craft Solo  | 3.5.0
Yii | 2.0.36
Twig | 2.12.5
Guzzle | 6.5.3
Imagine | 1.2.3-dev

**Comment by aelvan** [comment]
I don't think this is related to 3.5, and I think there's some other underlying issue here, according to your stacktrace, you're passing in `'Synced sequence...'` (as a string) to `transformImage`. This triggered an error in Imager because it got interpreted as a local file without an extension. I've fixed this issue in 3.1.3 (ie, Imager now works with valid local images that don't have an extension), but you'll now probably get another error saying that `'Synced sequence...'` does not exist or something.

What are you trying to transform, is it assets (local or remote?), a local file or an external file? I'd start by trying to identify exactly where in your templates this is happening, and drill down from there trying to identify why this string is being passed in instead of a valid image.
