### ISSUE TITLE
`Invalid transformer "craft"` errors in my logs.

### ISSUE THREAD

**Issue by bossanova808** [spacecatninja/craft-imager-x#56]
### I'm submitting a... 

- [X] bug report
- [ ] feature request
- [ ] general question

### Description

I am seeing a bunch of `Invalid transformer "craft"` errors in my logs.

This does not really make sense to me...?  It doesn't seem to be causing any functional issues, that I can detect - but it's a confusing log message for what I presume is the default transform service (I am not using IMGIX or anything else...)

### Displayed errors, stack trace, relevant logs  

```
2020-10-07 11:59:35 [-][4267][27e0dc489ee3eadcfae64aae9e8fecc3][error][spacecatninja\imagerx\services\ImagerService::transformImage] Invalid transformer "craft".
2020-10-07 11:59:35 [-][4267][27e0dc489ee3eadcfae64aae9e8fecc3][error][Twig\Error\RuntimeError] spacecatninja\imagerx\exceptions\ImagerException: Invalid transformer "craft". in /srv/users/serverpilot/apps/imagescience/releases/dev/vendor/spacecatninja/imager-x/src/services/ImagerService.php:422
Stack trace:
#0 /srv/users/serverpilot/apps/imagescience/releases/dev/vendor/spacecatninja/imager-x/src/variables/ImagerVariable.php(38): spacecatninja\imagerx\services\ImagerService->transformImage(Object(craft\elements\Asset), Array, Array, Array)
#1 /srv/users/serverpilot/apps/imagescience/releases/dev/vendor/twig/twig/src/Extension/CoreExtension.php(1499): spacecatninja\imagerx\variables\ImagerVariable->transformImage(Object(craft\elements\Asset), 'masthead')
#2 /srv/users/serverpilot/apps/imagescience/releases/dev/vendor/craftcms/cms/src/helpers/Template.php(92): twig_get_attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(spacecatninja\imagerx\variables\ImagerVariable), 'transformImage', Array, 'method', false, false)
#3 /srv/users/serverpilot/apps/imagescience/releases/dev/storage/runtime/compiled_templates/6a/6a414b89ebad3d336ac7dd6bb612f1535429ae37c1f587e4e76eac4819b3c110.php(317): craft\helpers\Template::attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(spacecatninja\imagerx\variables\ImagerVariable), 'transformImage', Array, 'method')
#4 /srv/users/serverpilot/apps/imagescience/releases/dev/vendor/twig/twig/src/Template.php(405): __TwigTemplate_da57e3f8786ecce0035099628d540a0a403ab249f41c8eb1ddc1935bb0d58884->doDisplay(Array, Array)
#5 /srv/users/serverpilot/apps/imagescience/releases/dev/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#6 /srv/users/serverpilot/apps/imagescience/releases/dev/storage/runtime/compiled_templates/c6/c6b90475e6124052fae9c54d6154e5d3963593a740a6989ba503e29c2dac01c2.php(232): Twig\Template->display(Array)
#7 /srv/users/serverpilot/apps/imagescience/releases/dev/vendor/twig/twig/src/Template.php(405): __TwigTemplate_670d16af97c4f167b842740f9601b4505f0fb26390ab7543b2a50125b926f1bf->doDisplay(Array, Array)
#8 /srv/users/serverpilot/apps/imagescience/releases/dev/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#9 /srv/users/serverpilot/apps/imagescience/releases/dev/storage/runtime/compiled_templates/9f/9f4f668dac52e85d45290a69cb7e83498fee45cf76cc54ce9bd37bcb0f5dc14e.php(52): Twig\Template->display(Array, Array)
#10 /srv/users/serverpilot/apps/imagescience/releases/dev/vendor/twig/twig/src/Template.php(405): __TwigTemplate_ec77f8af83faa58526ba0e44e171d11f688b49ab99743352089f76aa2dd58d1e->doDisplay(Array, Array)
#11 /srv/users/serverpilot/apps/imagescience/releases/dev/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#12 /srv/users/serverpilot/apps/imagescience/releases/dev/vendor/twig/twig/src/Template.php(390): Twig\Template->display(Array)
#13 /srv/users/serverpilot/apps/imagescience/releases/dev/vendor/twig/twig/src/TemplateWrapper.php(45): Twig\Template->render(Array, Array)
#14 /srv/users/serverpilot/apps/imagescience/releases/dev/vendor/twig/twig/src/Environment.php(318): Twig\TemplateWrapper->render(Array)
#15 /srv/users/serverpilot/apps/imagescience/releases/dev/vendor/craftcms/cms/src/web/View.php(392): Twig\Environment->render('_http-errors/50...', Array)
#16 /srv/users/serverpilot/apps/imagescience/releases/dev/vendor/craftcms/cms/src/web/View.php(453): craft\web\View->renderTemplate('_http-errors/50...', Array)
#17 /srv/users/serverpilot/apps/imagescience/releases/dev/vendor/craftcms/cms/src/web/Controller.php(251): craft\web\View->renderPageTemplate('_http-errors/50...', Array, 'site')
#18 /srv/users/serverpilot/apps/imagescience/releases/dev/vendor/craftcms/cms/src/controllers/TemplatesController.php(231): craft\web\Controller->renderTemplate('_http-errors/50...', Array)
#19 [internal function]: craft\controllers\TemplatesController->actionRenderError()
#20 /srv/users/serverpilot/apps/imagescience/releases/dev/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#21 /srv/users/serverpilot/apps/imagescience/releases/dev/vendor/yiisoft/yii2/base/Controller.php(180): yii\base\InlineAction->runWithParams(Array)
#22 /srv/users/serverpilot/apps/imagescience/releases/dev/vendor/craftcms/cms/src/web/Controller.php(189): yii\base\Controller->runAction('render-error', Array)
#23 /srv/users/serverpilot/apps/imagescience/releases/dev/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('render-error', Array)
#24 /srv/users/serverpilot/apps/imagescience/releases/dev/vendor/craftcms/cms/src/web/Application.php(274): yii\base\Module->runAction('templates/rende...', Array)
#25 /srv/users/serverpilot/apps/imagescience/releases/dev/vendor/yiisoft/yii2/web/ErrorHandler.php(109): craft\web\Application->runAction('templates/rende...')
#26 /srv/users/serverpilot/apps/imagescience/releases/dev/vendor/craftcms/cms/src/web/ErrorHandler.php(139): yii\web\ErrorHandler->renderException(Object(yii\base\ErrorException))
#27 /srv/users/serverpilot/apps/imagescience/releases/dev/vendor/yiisoft/yii2/base/ErrorHandler.php(135): craft\web\ErrorHandler->renderException(Object(yii\base\ErrorException))
#28 /srv/users/serverpilot/apps/imagescience/releases/dev/vendor/craftcms/cms/src/web/ErrorHandler.php(63): yii\base\ErrorHandler->handleException(Object(yii\base\ErrorException))
#29 [internal function]: craft\web\ErrorHandler->handleException(Object(yii\base\ErrorException))
#30 {main}
```

### Additional info

![image](https://user-images.githubusercontent.com/731309/95527349-c0836580-0a20-11eb-83c1-42ea510b880f.png)

**Comment by aelvan** [comment]
Yeah, that's a weird one. But, the default `craft` transformer is registered the same way as custom ones, and this happen's in the Craft event `Plugins::EVENT_AFTER_LOAD_PLUGINS`. Judging from the stacktrace, it looks like the Imager-error is thrown when trying to render a Craft error. And that you have a custom HTTP 50X error template (_http-errors/50...), is that correct? Do you have an image transform inside that template?

**Comment by bossanova808** [comment]
Hmm, yes I do use an imager transform in my error templates.  

So Imager is not loaded (or is loaded too late) in that case I guess?

**Comment by aelvan** [comment]
Yeah, can you see from your logs what error triggers the 500?

**Comment by aelvan** [comment]
I'll tag this as an enhancement, I think I can have the craft transformer registered even though the initialization doesn't happen. There might be other things failing still though.

**Comment by bossanova808** [comment]
Yep looking deeper the errors above these seem to be deployment related...in any case at the moment they're not cropping up during other moments that I can see, in recent logs.  99.999% sure they're not affecting anything the user ever actually sees really, so not a major concern from my end.  Thanks for looking into it.

**Comment by aelvan** [comment]
As of v3.2.4, the default `craft` transformer is registered statically (ie. as early as possible) in the list of transformers, so it should be available even if the event that registers transformers doesn't fire (which I think is the cause for this issue). But as I said, other things could also be failing that would still bar you from using Imager in the event of a HTTP 500 error.
